package net.averak.gsync.infrastructure.mybatis.plugin

import org.mybatis.generator.api.IntrospectedTable
import org.mybatis.generator.api.PluginAdapter
import org.mybatis.generator.api.dom.java.*
import org.mybatis.generator.api.dom.xml.Attribute
import org.mybatis.generator.api.dom.xml.Document
import org.mybatis.generator.api.dom.xml.TextElement
import org.mybatis.generator.api.dom.xml.XmlElement

/**
 * Bulk Insert 関連コードを生成するプラグイン
 */
class BulkInsertPlugin : PluginAdapter() {

    override fun validate(warnings: List<String>): Boolean {
        return true
    }

    override fun clientGenerated(interfaze: Interface, introspectedTable: IntrospectedTable): Boolean {
        interfaze.addImportedType(FullyQualifiedJavaType("java.util.List"))

        val method = Method("bulkInsert")
        method.visibility = JavaVisibility.PUBLIC
        method.isAbstract = true
        method.addParameter(
            Parameter(FullyQualifiedJavaType("List<${introspectedTable.baseRecordType}>"), "dtos").apply {
                addAnnotation("@Param(\"dtos\")")
            },
        )
        method.setReturnType(FullyQualifiedJavaType("void"))

        method.javaDocLines += "/**"
        method.javaDocLines += " * 複数レコードを一括で INSERT する"
        method.javaDocLines += " *"
        method.javaDocLines += " * @mbg.generated"
        method.javaDocLines += " */"

        interfaze.addMethod(method)

        return super.clientGenerated(interfaze, introspectedTable)
    }

    override fun sqlMapDocumentGenerated(document: Document, introspectedTable: IntrospectedTable): Boolean {
        val element = XmlElement("insert")
        element.addAttribute(Attribute("id", "bulkInsert"))
        element.addElement(TextElement("<!--"))
        element.addElement(TextElement("  WARNING - @mbg.generated"))
        element.addElement(TextElement("  This element is generated by BulkInsertPlugin."))
        element.addElement(TextElement("-->"))

        element.addElement(TextElement("INSERT INTO " + introspectedTable.fullyQualifiedTableNameAtRuntime))
        element.addElement(
            TextElement(
                "(${introspectedTable.allColumns.joinToString(", ") { it.actualColumnName }})",
            ),
        )
        element.addElement(TextElement("VALUES"))

        val forEachElement = XmlElement("foreach")
        forEachElement.addAttribute(Attribute("collection", "dtos"))
        forEachElement.addAttribute(Attribute("item", "dto"))
        forEachElement.addAttribute(Attribute("separator", ","))
        forEachElement.addElement(
            TextElement(
                "(${introspectedTable.allColumns.joinToString(", ") { "#{dto.${it.javaProperty}, jdbcType=${it.jdbcTypeName}}" }})",
            ),
        )

        element.addElement(forEachElement)

        document.rootElement.addElement(element)

        return super.sqlMapDocumentGenerated(document, introspectedTable)
    }
}
