package net.averak.gsync.adapter.dao.dto.base;

import java.time.LocalDateTime;
import java.util.Objects;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class FriendSettingMasterDto extends AbstractDto<FriendSettingMasterDto> {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_friend_setting_master.master_version
	 *
	 * @mbg.generated
	 */
	private String masterVersion;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_friend_setting_master.max_friend_count
	 *
	 * @mbg.generated
	 */
	private Long maxFriendCount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_friend_setting_master.max_friend_request_count
	 *
	 * @mbg.generated
	 */
	private Long maxFriendRequestCount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_friend_setting_master.created_at
	 *
	 * @mbg.generated
	 */
	private LocalDateTime createdAt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_friend_setting_master.updated_at
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_friend_setting_master
	 *
	 * @mbg.generated
	 */
	public FriendSettingMasterDto(@Nonnull String masterVersion, @Nonnull Long maxFriendCount,
			@Nonnull Long maxFriendRequestCount, @Nonnull LocalDateTime createdAt, @Nonnull LocalDateTime updatedAt) {
		this.masterVersion = masterVersion;
		this.maxFriendCount = maxFriendCount;
		this.maxFriendRequestCount = maxFriendRequestCount;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_friend_setting_master
	 *
	 * @mbg.generated
	 */
	public FriendSettingMasterDto() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_friend_setting_master.master_version
	 *
	 * @return the value of gsync_friend_setting_master.master_version
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public String getMasterVersion() {
		return masterVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_friend_setting_master.master_version
	 *
	 * @param masterVersion
	 *            the value for gsync_friend_setting_master.master_version
	 *
	 * @mbg.generated
	 */
	public void setMasterVersion(@Nonnull String masterVersion) {
		this.masterVersion = masterVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_friend_setting_master.max_friend_count
	 *
	 * @return the value of gsync_friend_setting_master.max_friend_count
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public Long getMaxFriendCount() {
		return maxFriendCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_friend_setting_master.max_friend_count
	 *
	 * @param maxFriendCount
	 *            the value for gsync_friend_setting_master.max_friend_count
	 *
	 * @mbg.generated
	 */
	public void setMaxFriendCount(@Nonnull Long maxFriendCount) {
		this.maxFriendCount = maxFriendCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_friend_setting_master.max_friend_request_count
	 *
	 * @return the value of gsync_friend_setting_master.max_friend_request_count
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public Long getMaxFriendRequestCount() {
		return maxFriendRequestCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_friend_setting_master.max_friend_request_count
	 *
	 * @param maxFriendRequestCount
	 *            the value for gsync_friend_setting_master.max_friend_request_count
	 *
	 * @mbg.generated
	 */
	public void setMaxFriendRequestCount(@Nonnull Long maxFriendRequestCount) {
		this.maxFriendRequestCount = maxFriendRequestCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_friend_setting_master.created_at
	 *
	 * @return the value of gsync_friend_setting_master.created_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_friend_setting_master.created_at
	 *
	 * @param createdAt
	 *            the value for gsync_friend_setting_master.created_at
	 *
	 * @mbg.generated
	 */
	public void setCreatedAt(@Nonnull LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_friend_setting_master.updated_at
	 *
	 * @return the value of gsync_friend_setting_master.updated_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_friend_setting_master.updated_at
	 *
	 * @param updatedAt
	 *            the value for gsync_friend_setting_master.updated_at
	 *
	 * @mbg.generated
	 */
	public void setUpdatedAt(@Nonnull LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	public boolean isPrimaryKeyEquals(FriendSettingMasterDto other) {
		return Objects.equals(getMasterVersion(), other.getMasterVersion());
	}
}