package net.averak.gsync.adapter.dao.dto.base;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

@SuppressWarnings({"all"})
public class MasterVersionDto extends AbstractDto<MasterVersionDto> implements Serializable {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_master_version.version
	 *
	 * @mbg.generated
	 */
	@Nonnull
	private String version;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_master_version.is_valid
	 *
	 * @mbg.generated
	 */
	@Nonnull
	private Boolean isValid;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_master_version.comment
	 *
	 * @mbg.generated
	 */
	@Nonnull
	private String comment;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_master_version.created_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	private LocalDateTime createdAt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_master_version.updated_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	private LocalDateTime updatedAt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	public MasterVersionDto(@Nonnull String version, @Nonnull Boolean isValid, @Nonnull String comment,
			@Nonnull LocalDateTime createdAt, @Nonnull LocalDateTime updatedAt) {
		this.version = version;
		this.isValid = isValid;
		this.comment = comment;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	public MasterVersionDto() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_master_version.version
	 *
	 * @return the value of gsync_master_version.version
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_master_version.version
	 *
	 * @param version
	 *            the value for gsync_master_version.version
	 *
	 * @mbg.generated
	 */
	public void setVersion(@Nonnull String version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_master_version.is_valid
	 *
	 * @return the value of gsync_master_version.is_valid
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public Boolean getIsValid() {
		return isValid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_master_version.is_valid
	 *
	 * @param isValid
	 *            the value for gsync_master_version.is_valid
	 *
	 * @mbg.generated
	 */
	public void setIsValid(@Nonnull Boolean isValid) {
		this.isValid = isValid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_master_version.comment
	 *
	 * @return the value of gsync_master_version.comment
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_master_version.comment
	 *
	 * @param comment
	 *            the value for gsync_master_version.comment
	 *
	 * @mbg.generated
	 */
	public void setComment(@Nonnull String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_master_version.created_at
	 *
	 * @return the value of gsync_master_version.created_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_master_version.created_at
	 *
	 * @param createdAt
	 *            the value for gsync_master_version.created_at
	 *
	 * @mbg.generated
	 */
	public void setCreatedAt(@Nonnull LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_master_version.updated_at
	 *
	 * @return the value of gsync_master_version.updated_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_master_version.updated_at
	 *
	 * @param updatedAt
	 *            the value for gsync_master_version.updated_at
	 *
	 * @mbg.generated
	 */
	public void setUpdatedAt(@Nonnull LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * PK が一致するか判定
	 *
	 * @mbg.generated
	 */
	public boolean isPrimaryKeyEquals(MasterVersionDto other) {
		return Objects.equals(getVersion(), other.getVersion());
	}

	/**
	 * マジックカラムにデフォルト値を設定するコンストラクタ
	 *
	 * @mbg.generated
	 */
	public MasterVersionDto(@Nonnull String version, @Nonnull Boolean isValid, @Nonnull String comment) {
		this.version = version;
		this.isValid = isValid;
		this.comment = comment;
		this.createdAt = LocalDateTime.now();
		this.updatedAt = LocalDateTime.now();
	}
}