package net.averak.gsync.adapter.dao.dto.base;

import java.time.LocalDateTime;
import java.util.Objects;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

@SuppressWarnings({"all"})
public class PlayerProfileDto extends AbstractDto<PlayerProfileDto> {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_player_profile.player_id
	 *
	 * @mbg.generated
	 */
	private String playerId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_player_profile.nickname
	 *
	 * @mbg.generated
	 */
	private String nickname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_player_profile.icon_id
	 *
	 * @mbg.generated
	 */
	private String iconId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_player_profile.created_at
	 *
	 * @mbg.generated
	 */
	private LocalDateTime createdAt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_player_profile.updated_at
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	public PlayerProfileDto(@Nonnull String playerId, @Nonnull String nickname, @Nonnull String iconId,
			@Nonnull LocalDateTime createdAt, @Nonnull LocalDateTime updatedAt) {
		this.playerId = playerId;
		this.nickname = nickname;
		this.iconId = iconId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	public PlayerProfileDto() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_player_profile.player_id
	 *
	 * @return the value of gsync_player_profile.player_id
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public String getPlayerId() {
		return playerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_player_profile.player_id
	 *
	 * @param playerId
	 *            the value for gsync_player_profile.player_id
	 *
	 * @mbg.generated
	 */
	public void setPlayerId(@Nonnull String playerId) {
		this.playerId = playerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_player_profile.nickname
	 *
	 * @return the value of gsync_player_profile.nickname
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_player_profile.nickname
	 *
	 * @param nickname
	 *            the value for gsync_player_profile.nickname
	 *
	 * @mbg.generated
	 */
	public void setNickname(@Nonnull String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_player_profile.icon_id
	 *
	 * @return the value of gsync_player_profile.icon_id
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public String getIconId() {
		return iconId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_player_profile.icon_id
	 *
	 * @param iconId
	 *            the value for gsync_player_profile.icon_id
	 *
	 * @mbg.generated
	 */
	public void setIconId(@Nonnull String iconId) {
		this.iconId = iconId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_player_profile.created_at
	 *
	 * @return the value of gsync_player_profile.created_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_player_profile.created_at
	 *
	 * @param createdAt
	 *            the value for gsync_player_profile.created_at
	 *
	 * @mbg.generated
	 */
	public void setCreatedAt(@Nonnull LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_player_profile.updated_at
	 *
	 * @return the value of gsync_player_profile.updated_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_player_profile.updated_at
	 *
	 * @param updatedAt
	 *            the value for gsync_player_profile.updated_at
	 *
	 * @mbg.generated
	 */
	public void setUpdatedAt(@Nonnull LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * PK が一致するか判定
	 *
	 * @mbg.generated
	 */
	public boolean isPrimaryKeyEquals(PlayerProfileDto other) {
		return Objects.equals(getPlayerId(), other.getPlayerId());
	}
}