package net.averak.gsync.adapter.dao.dto.base;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PlayerFriendExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public PlayerFriendExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPlayerIdIsNull() {
			addCriterion("`player_id` is null");
			return (Criteria) this;
		}

		public Criteria andPlayerIdIsNotNull() {
			addCriterion("`player_id` is not null");
			return (Criteria) this;
		}

		public Criteria andPlayerIdEqualTo(String value) {
			addCriterion("`player_id` =", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotEqualTo(String value) {
			addCriterion("`player_id` <>", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdGreaterThan(String value) {
			addCriterion("`player_id` >", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdGreaterThanOrEqualTo(String value) {
			addCriterion("`player_id` >=", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLessThan(String value) {
			addCriterion("`player_id` <", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLessThanOrEqualTo(String value) {
			addCriterion("`player_id` <=", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdLike(String value) {
			addCriterion("`player_id` like", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotLike(String value) {
			addCriterion("`player_id` not like", value, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdIn(List<String> values) {
			addCriterion("`player_id` in", values, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotIn(List<String> values) {
			addCriterion("`player_id` not in", values, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdBetween(String value1, String value2) {
			addCriterion("`player_id` between", value1, value2, "playerId");
			return (Criteria) this;
		}

		public Criteria andPlayerIdNotBetween(String value1, String value2) {
			addCriterion("`player_id` not between", value1, value2, "playerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdIsNull() {
			addCriterion("`friend_player_id` is null");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdIsNotNull() {
			addCriterion("`friend_player_id` is not null");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdEqualTo(String value) {
			addCriterion("`friend_player_id` =", value, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdNotEqualTo(String value) {
			addCriterion("`friend_player_id` <>", value, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdGreaterThan(String value) {
			addCriterion("`friend_player_id` >", value, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdGreaterThanOrEqualTo(String value) {
			addCriterion("`friend_player_id` >=", value, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdLessThan(String value) {
			addCriterion("`friend_player_id` <", value, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdLessThanOrEqualTo(String value) {
			addCriterion("`friend_player_id` <=", value, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdLike(String value) {
			addCriterion("`friend_player_id` like", value, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdNotLike(String value) {
			addCriterion("`friend_player_id` not like", value, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdIn(List<String> values) {
			addCriterion("`friend_player_id` in", values, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdNotIn(List<String> values) {
			addCriterion("`friend_player_id` not in", values, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdBetween(String value1, String value2) {
			addCriterion("`friend_player_id` between", value1, value2, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andFriendPlayerIdNotBetween(String value1, String value2) {
			addCriterion("`friend_player_id` not between", value1, value2, "friendPlayerId");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtIsNull() {
			addCriterion("`become_friend_at` is null");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtIsNotNull() {
			addCriterion("`become_friend_at` is not null");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtEqualTo(LocalDateTime value) {
			addCriterion("`become_friend_at` =", value, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtNotEqualTo(LocalDateTime value) {
			addCriterion("`become_friend_at` <>", value, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtGreaterThan(LocalDateTime value) {
			addCriterion("`become_friend_at` >", value, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("`become_friend_at` >=", value, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtLessThan(LocalDateTime value) {
			addCriterion("`become_friend_at` <", value, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("`become_friend_at` <=", value, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtIn(List<LocalDateTime> values) {
			addCriterion("`become_friend_at` in", values, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtNotIn(List<LocalDateTime> values) {
			addCriterion("`become_friend_at` not in", values, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("`become_friend_at` between", value1, value2, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andBecomeFriendAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("`become_friend_at` not between", value1, value2, "becomeFriendAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("`created_at` is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("`created_at` is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(LocalDateTime value) {
			addCriterion("`created_at` =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(LocalDateTime value) {
			addCriterion("`created_at` <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(LocalDateTime value) {
			addCriterion("`created_at` >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("`created_at` >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(LocalDateTime value) {
			addCriterion("`created_at` <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("`created_at` <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<LocalDateTime> values) {
			addCriterion("`created_at` in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<LocalDateTime> values) {
			addCriterion("`created_at` not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("`created_at` between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("`created_at` not between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNull() {
			addCriterion("`updated_at` is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIsNotNull() {
			addCriterion("`updated_at` is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtEqualTo(LocalDateTime value) {
			addCriterion("`updated_at` =", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotEqualTo(LocalDateTime value) {
			addCriterion("`updated_at` <>", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThan(LocalDateTime value) {
			addCriterion("`updated_at` >", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("`updated_at` >=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThan(LocalDateTime value) {
			addCriterion("`updated_at` <", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("`updated_at` <=", value, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtIn(List<LocalDateTime> values) {
			addCriterion("`updated_at` in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotIn(List<LocalDateTime> values) {
			addCriterion("`updated_at` not in", values, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("`updated_at` between", value1, value2, "updatedAt");
			return (Criteria) this;
		}

		public Criteria andUpdatedAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("`updated_at` not between", value1, value2, "updatedAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table gsync_player_friend
	 *
	 * @mbg.generated do_not_delete_during_merge
	 */
	public static class Criteria extends GeneratedCriteria {
		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}