package net.averak.gsync.adapter.dao.dto.base;

import java.time.LocalDateTime;
import java.util.Objects;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

@SuppressWarnings({"all"})
public class RGameOperatorDto extends AbstractDto<RGameOperatorDto> {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_r_game_operator.operator_id
	 *
	 * @mbg.generated
	 */
	private String operatorId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_r_game_operator.game_id
	 *
	 * @mbg.generated
	 */
	private String gameId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_r_game_operator.is_admin
	 *
	 * @mbg.generated
	 */
	private Boolean isAdmin;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_r_game_operator.created_at
	 *
	 * @mbg.generated
	 */
	private LocalDateTime createdAt;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column gsync_r_game_operator.updated_at
	 *
	 * @mbg.generated
	 */
	private LocalDateTime updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	public RGameOperatorDto(@Nonnull String operatorId, @Nonnull String gameId, @Nonnull Boolean isAdmin,
			@Nonnull LocalDateTime createdAt, @Nonnull LocalDateTime updatedAt) {
		this.operatorId = operatorId;
		this.gameId = gameId;
		this.isAdmin = isAdmin;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	public RGameOperatorDto() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_r_game_operator.operator_id
	 *
	 * @return the value of gsync_r_game_operator.operator_id
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_r_game_operator.operator_id
	 *
	 * @param operatorId
	 *            the value for gsync_r_game_operator.operator_id
	 *
	 * @mbg.generated
	 */
	public void setOperatorId(@Nonnull String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_r_game_operator.game_id
	 *
	 * @return the value of gsync_r_game_operator.game_id
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public String getGameId() {
		return gameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_r_game_operator.game_id
	 *
	 * @param gameId
	 *            the value for gsync_r_game_operator.game_id
	 *
	 * @mbg.generated
	 */
	public void setGameId(@Nonnull String gameId) {
		this.gameId = gameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_r_game_operator.is_admin
	 *
	 * @return the value of gsync_r_game_operator.is_admin
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public Boolean getIsAdmin() {
		return isAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_r_game_operator.is_admin
	 *
	 * @param isAdmin
	 *            the value for gsync_r_game_operator.is_admin
	 *
	 * @mbg.generated
	 */
	public void setIsAdmin(@Nonnull Boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_r_game_operator.created_at
	 *
	 * @return the value of gsync_r_game_operator.created_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_r_game_operator.created_at
	 *
	 * @param createdAt
	 *            the value for gsync_r_game_operator.created_at
	 *
	 * @mbg.generated
	 */
	public void setCreatedAt(@Nonnull LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column gsync_r_game_operator.updated_at
	 *
	 * @return the value of gsync_r_game_operator.updated_at
	 *
	 * @mbg.generated
	 */
	@Nonnull
	public LocalDateTime getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column gsync_r_game_operator.updated_at
	 *
	 * @param updatedAt
	 *            the value for gsync_r_game_operator.updated_at
	 *
	 * @mbg.generated
	 */
	public void setUpdatedAt(@Nonnull LocalDateTime updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * PK が一致するか判定
	 *
	 * @mbg.generated
	 */
	public boolean isPrimaryKeyEquals(RGameOperatorDto other) {
		return Objects.equals(getOperatorId(), other.getOperatorId()) && Objects.equals(getGameId(), other.getGameId());
	}

	/**
	 * マジックカラムにデフォルト値を設定するコンストラクタ
	 *
	 * @mbg.generated
	 */
	public RGameOperatorDto(@Nonnull String operatorId, @Nonnull String gameId, @Nonnull Boolean isAdmin) {
		this.operatorId = operatorId;
		this.gameId = gameId;
		this.isAdmin = isAdmin;
		this.createdAt = LocalDateTime.now();
		this.updatedAt = LocalDateTime.now();
	}
}