// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_api/echo.proto

// Protobuf Java Version: 3.25.1
package net.averak.gsync.schema.protobuf.player_api;

public final class EchoOuterClass {
	private EchoOuterClass() {
	}
	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_EchoEchoV1_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_EchoEchoV1_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_EchoEchoV1_Request_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_EchoEchoV1_Request_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_EchoEchoV1_Response_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_EchoEchoV1_Response_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}
	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {"\n\025player_api/echo.proto\022\020gsync.player_ap"
				+ "i\032\037google/protobuf/timestamp.proto\"t\n\nEc"
				+ "hoEchoV1\032\032\n\007Request\022\017\n\007message\030\001 \001(\t\032J\n\010"
				+ "Response\022\017\n\007message\030\001 \001(\t\022-\n\ttimestamp\030\002"
				+ " \001(\0132\032.google.protobuf.Timestamp2]\n\004Echo"
				+ "\022U\n\006EchoV1\022$.gsync.player_api.EchoEchoV1" + ".Request\032%.gsync.player_api.EchoEchoV1.R"
				+ "esponseB/\n+net.averak.gsync.schema.proto" + "buf.player_apiP\001b\006proto3"};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[]{
						com.google.protobuf.TimestampProto.getDescriptor(),});
		internal_static_gsync_player_api_EchoEchoV1_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_gsync_player_api_EchoEchoV1_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_EchoEchoV1_descriptor, new java.lang.String[]{});
		internal_static_gsync_player_api_EchoEchoV1_Request_descriptor = internal_static_gsync_player_api_EchoEchoV1_descriptor
				.getNestedTypes().get(0);
		internal_static_gsync_player_api_EchoEchoV1_Request_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_EchoEchoV1_Request_descriptor, new java.lang.String[]{"Message",});
		internal_static_gsync_player_api_EchoEchoV1_Response_descriptor = internal_static_gsync_player_api_EchoEchoV1_descriptor
				.getNestedTypes().get(1);
		internal_static_gsync_player_api_EchoEchoV1_Response_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_EchoEchoV1_Response_descriptor,
				new java.lang.String[]{"Message", "Timestamp",});
		com.google.protobuf.TimestampProto.getDescriptor();
	}

	// @@protoc_insertion_point(outer_class_scope)
}
