// Generated by protoc-gen-java-gsync-server. DO NOT EDIT!
// source: player_api/echo.proto
package net.averak.gsync.schema.protobuf.player_api;

import io.grpc.stub.StreamObserver;
import net.averak.gsync.infrastructure.grpc.player_api.HandlerWrapper;
import net.averak.gsync.infrastructure.grpc.player_api.Request;
import org.springframework.stereotype.Component;

@Component
public class EchoHandlerWrapper extends EchoGrpc.EchoImplBase {
	private final HandlerWrapper handlerWrapper;
	private final IEchoHandler handler;

	public EchoHandlerWrapper(HandlerWrapper handlerWrapper, IEchoHandler handler) {
		this.handlerWrapper = handlerWrapper;
		this.handler = handler;
	}

	@Override
	public void echoV1(EchoEchoV1.Request request, StreamObserver<EchoEchoV1.Response> responseObserver) {
		handlerWrapper.invoke(handler::echoV1, request, responseObserver);
	}

}
