// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_api/friend.proto

// Protobuf Java Version: 3.25.2
package net.averak.gsync.schema.protobuf.player_api;

public final class FriendOuterClass {
	private FriendOuterClass() {
	}
	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_FriendListV1_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_FriendListV1_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_FriendListV1_Request_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_FriendListV1_Request_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_FriendListV1_Response_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_FriendListV1_Response_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_FriendSendRequestV1_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_FriendSendRequestV1_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_FriendSendRequestV1_Request_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_FriendSendRequestV1_Request_fieldAccessorTable;
	static final com.google.protobuf.Descriptors.Descriptor internal_static_gsync_player_api_FriendSendRequestV1_Response_descriptor;
	static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_gsync_player_api_FriendSendRequestV1_Response_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}
	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {"\n\027player_api/friend.proto\022\020gsync.player_"
				+ "api\032\025resource/friend.proto\"\342\001\n\014FriendLis"
				+ "tV1\032\t\n\007Request\032\306\001\n\010Response\022.\n\007friends\030\001"
				+ " \003(\0132\035.gsync.resource.friend.Friend\022B\n\024s"
				+ "ent_friend_requests\030\002 \003(\0132$.gsync.resour"
				+ "ce.friend.FriendRequest\022F\n\030received_frie"
				+ "nd_requests\030\003 \003(\0132$.gsync.resource.frien"
				+ "d.FriendRequest\"?\n\023FriendSendRequestV1\032\034"
				+ "\n\007Request\022\021\n\tplayer_id\030\001 \001(\t\032\n\n\010Response"
				+ "2\323\001\n\006Friend\022Y\n\006ListV1\022&.gsync.player_api"
				+ ".FriendListV1.Request\032\'.gsync.player_api" + ".FriendListV1.Response\022n\n\rSendRequestV1\022"
				+ "-.gsync.player_api.FriendSendRequestV1.R" + "equest\032..gsync.player_api.FriendSendRequ"
				+ "estV1.ResponseB/\n+net.averak.gsync.schem" + "a.protobuf.player_apiP\001b\006proto3"};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[]{
						net.averak.gsync.schema.protobuf.resource.friend.FriendOuterClass.getDescriptor(),});
		internal_static_gsync_player_api_FriendListV1_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_gsync_player_api_FriendListV1_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_FriendListV1_descriptor, new java.lang.String[]{});
		internal_static_gsync_player_api_FriendListV1_Request_descriptor = internal_static_gsync_player_api_FriendListV1_descriptor
				.getNestedTypes().get(0);
		internal_static_gsync_player_api_FriendListV1_Request_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_FriendListV1_Request_descriptor, new java.lang.String[]{});
		internal_static_gsync_player_api_FriendListV1_Response_descriptor = internal_static_gsync_player_api_FriendListV1_descriptor
				.getNestedTypes().get(1);
		internal_static_gsync_player_api_FriendListV1_Response_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_FriendListV1_Response_descriptor,
				new java.lang.String[]{"Friends", "SentFriendRequests", "ReceivedFriendRequests",});
		internal_static_gsync_player_api_FriendSendRequestV1_descriptor = getDescriptor().getMessageTypes().get(1);
		internal_static_gsync_player_api_FriendSendRequestV1_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_FriendSendRequestV1_descriptor, new java.lang.String[]{});
		internal_static_gsync_player_api_FriendSendRequestV1_Request_descriptor = internal_static_gsync_player_api_FriendSendRequestV1_descriptor
				.getNestedTypes().get(0);
		internal_static_gsync_player_api_FriendSendRequestV1_Request_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_FriendSendRequestV1_Request_descriptor,
				new java.lang.String[]{"PlayerId",});
		internal_static_gsync_player_api_FriendSendRequestV1_Response_descriptor = internal_static_gsync_player_api_FriendSendRequestV1_descriptor
				.getNestedTypes().get(1);
		internal_static_gsync_player_api_FriendSendRequestV1_Response_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_gsync_player_api_FriendSendRequestV1_Response_descriptor, new java.lang.String[]{});
		net.averak.gsync.schema.protobuf.resource.friend.FriendOuterClass.getDescriptor();
	}

	// @@protoc_insertion_point(outer_class_scope)
}
