// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_api/friend.proto

// Protobuf Java Version: 3.25.2
package net.averak.gsync.schema.protobuf.player_api;

public interface FriendListV1OrBuilder
		extends
			// @@protoc_insertion_point(interface_extends:gsync.player_api.FriendListV1)
			com.google.protobuf.MessageOrBuilder {
}
