// Generated by protoc-gen-java-gsync-server. DO NOT EDIT!
// source: player_api/friend.proto
package net.averak.gsync.schema.protobuf.player_api;

import io.grpc.stub.StreamObserver;
import net.averak.gsync.infrastructure.grpc.player_api.HandlerWrapper;
import net.averak.gsync.infrastructure.grpc.player_api.Request;
import org.springframework.stereotype.Component;

@Component
public class FriendHandlerWrapper extends FriendGrpc.FriendImplBase {
	private final HandlerWrapper handlerWrapper;
	private final IFriendHandler handler;

	public FriendHandlerWrapper(HandlerWrapper handlerWrapper, IFriendHandler handler) {
		this.handlerWrapper = handlerWrapper;
		this.handler = handler;
	}

	@Override
	public void listV1(FriendListV1.Request request, StreamObserver<FriendListV1.Response> responseObserver) {
		handlerWrapper.invoke(handler::listV1, request, responseObserver);
	}

}
