// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_api/friend.proto

// Protobuf Java Version: 3.25.2
package net.averak.gsync.schema.protobuf.player_api;

/**
 * Protobuf type {@code gsync.player_api.FriendListV1}
 */
public final class FriendListV1 extends com.google.protobuf.GeneratedMessageV3
		implements
			// @@protoc_insertion_point(message_implements:gsync.player_api.FriendListV1)
			FriendListV1OrBuilder {
	private static final long serialVersionUID = 0L;
	// Use FriendListV1.newBuilder() to construct.
	private FriendListV1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}
	private FriendListV1() {
	}

	@java.lang.Override
	@SuppressWarnings({"unused"})
	protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
		return new FriendListV1();
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_fieldAccessorTable
				.ensureFieldAccessorsInitialized(net.averak.gsync.schema.protobuf.player_api.FriendListV1.class,
						net.averak.gsync.schema.protobuf.player_api.FriendListV1.Builder.class);
	}

	public interface RequestOrBuilder
			extends
				// @@protoc_insertion_point(interface_extends:gsync.player_api.FriendListV1.Request)
				com.google.protobuf.MessageOrBuilder {
	}
	/**
	 * Protobuf type {@code gsync.player_api.FriendListV1.Request}
	 */
	public static final class Request extends com.google.protobuf.GeneratedMessageV3
			implements
				// @@protoc_insertion_point(message_implements:gsync.player_api.FriendListV1.Request)
				RequestOrBuilder {
		private static final long serialVersionUID = 0L;
		// Use Request.newBuilder() to construct.
		private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}
		private Request() {
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
			return new Request();
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Request_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Request_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request.class,
							net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request.Builder.class);
		}

		private byte memoizedIsInitialized = -1;
		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getUnknownFields().writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request)) {
				return super.equals(obj);
			}
			net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request other = (net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request) obj;

			if (!getUnknownFields().equals(other.getUnknownFields()))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(
				java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(
				java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}
		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}
		public static Builder newBuilder(net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}
		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		/**
		 * Protobuf type {@code gsync.player_api.FriendListV1.Request}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
				implements
					// @@protoc_insertion_point(builder_implements:gsync.player_api.FriendListV1.Request)
					net.averak.gsync.schema.protobuf.player_api.FriendListV1.RequestOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Request_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Request_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request.class,
								net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request.Builder.class);
			}

			// Construct using
			// net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request.newBuilder()
			private Builder() {

			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);

			}
			@java.lang.Override
			public Builder clear() {
				super.clear();
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Request_descriptor;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request getDefaultInstanceForType() {
				return net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request.getDefaultInstance();
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request build() {
				net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request buildPartial() {
				net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request result = new net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request(
						this);
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}
			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}
			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}
			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}
			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}
			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}
			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request) {
					return mergeFrom((net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request other) {
				if (other == net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request.getDefaultInstance())
					return this;
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0 :
								done = true;
								break;
							default : {
								if (!super.parseUnknownField(input, extensionRegistry, tag)) {
									done = true; // was an endgroup tag
								}
								break;
							} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}
			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:gsync.player_api.FriendListV1.Request)
		}

		// @@protoc_insertion_point(class_scope:gsync.player_api.FriendListV1.Request)
		private static final net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request();
		}

		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Request> PARSER = new com.google.protobuf.AbstractParser<Request>() {
			@java.lang.Override
			public Request parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
							.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		public static com.google.protobuf.Parser<Request> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Request> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.FriendListV1.Request getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface ResponseOrBuilder
			extends
				// @@protoc_insertion_point(interface_extends:gsync.player_api.FriendListV1.Response)
				com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		java.util.List<net.averak.gsync.schema.protobuf.resource.friend.Friend> getFriendsList();
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.friend.Friend getFriends(int index);
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		int getFriendsCount();
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder> getFriendsOrBuilderList();
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder getFriendsOrBuilder(int index);

		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> getSentFriendRequestsList();
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.friend.FriendRequest getSentFriendRequests(int index);
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		int getSentFriendRequestsCount();
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> getSentFriendRequestsOrBuilderList();
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder getSentFriendRequestsOrBuilder(
				int index);

		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> getReceivedFriendRequestsList();
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.friend.FriendRequest getReceivedFriendRequests(int index);
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		int getReceivedFriendRequestsCount();
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> getReceivedFriendRequestsOrBuilderList();
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder getReceivedFriendRequestsOrBuilder(
				int index);
	}
	/**
	 * Protobuf type {@code gsync.player_api.FriendListV1.Response}
	 */
	public static final class Response extends com.google.protobuf.GeneratedMessageV3
			implements
				// @@protoc_insertion_point(message_implements:gsync.player_api.FriendListV1.Response)
				ResponseOrBuilder {
		private static final long serialVersionUID = 0L;
		// Use Response.newBuilder() to construct.
		private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}
		private Response() {
			friends_ = java.util.Collections.emptyList();
			sentFriendRequests_ = java.util.Collections.emptyList();
			receivedFriendRequests_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
			return new Response();
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Response_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Response_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response.class,
							net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response.Builder.class);
		}

		public static final int FRIENDS_FIELD_NUMBER = 1;
		@SuppressWarnings("serial")
		private java.util.List<net.averak.gsync.schema.protobuf.resource.friend.Friend> friends_;
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		@java.lang.Override
		public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.Friend> getFriendsList() {
			return friends_;
		}
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		@java.lang.Override
		public java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder> getFriendsOrBuilderList() {
			return friends_;
		}
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		@java.lang.Override
		public int getFriendsCount() {
			return friends_.size();
		}
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.friend.Friend getFriends(int index) {
			return friends_.get(index);
		}
		/**
		 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder getFriendsOrBuilder(int index) {
			return friends_.get(index);
		}

		public static final int SENT_FRIEND_REQUESTS_FIELD_NUMBER = 2;
		@SuppressWarnings("serial")
		private java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> sentFriendRequests_;
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		@java.lang.Override
		public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> getSentFriendRequestsList() {
			return sentFriendRequests_;
		}
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		@java.lang.Override
		public java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> getSentFriendRequestsOrBuilderList() {
			return sentFriendRequests_;
		}
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		@java.lang.Override
		public int getSentFriendRequestsCount() {
			return sentFriendRequests_.size();
		}
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest getSentFriendRequests(int index) {
			return sentFriendRequests_.get(index);
		}
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder getSentFriendRequestsOrBuilder(
				int index) {
			return sentFriendRequests_.get(index);
		}

		public static final int RECEIVED_FRIEND_REQUESTS_FIELD_NUMBER = 3;
		@SuppressWarnings("serial")
		private java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> receivedFriendRequests_;
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		@java.lang.Override
		public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> getReceivedFriendRequestsList() {
			return receivedFriendRequests_;
		}
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		@java.lang.Override
		public java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> getReceivedFriendRequestsOrBuilderList() {
			return receivedFriendRequests_;
		}
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		@java.lang.Override
		public int getReceivedFriendRequestsCount() {
			return receivedFriendRequests_.size();
		}
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest getReceivedFriendRequests(int index) {
			return receivedFriendRequests_.get(index);
		}
		/**
		 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder getReceivedFriendRequestsOrBuilder(
				int index) {
			return receivedFriendRequests_.get(index);
		}

		private byte memoizedIsInitialized = -1;
		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			for (int i = 0; i < friends_.size(); i++) {
				output.writeMessage(1, friends_.get(i));
			}
			for (int i = 0; i < sentFriendRequests_.size(); i++) {
				output.writeMessage(2, sentFriendRequests_.get(i));
			}
			for (int i = 0; i < receivedFriendRequests_.size(); i++) {
				output.writeMessage(3, receivedFriendRequests_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < friends_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, friends_.get(i));
			}
			for (int i = 0; i < sentFriendRequests_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, sentFriendRequests_.get(i));
			}
			for (int i = 0; i < receivedFriendRequests_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, receivedFriendRequests_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response)) {
				return super.equals(obj);
			}
			net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response other = (net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response) obj;

			if (!getFriendsList().equals(other.getFriendsList()))
				return false;
			if (!getSentFriendRequestsList().equals(other.getSentFriendRequestsList()))
				return false;
			if (!getReceivedFriendRequestsList().equals(other.getReceivedFriendRequestsList()))
				return false;
			if (!getUnknownFields().equals(other.getUnknownFields()))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (getFriendsCount() > 0) {
				hash = (37 * hash) + FRIENDS_FIELD_NUMBER;
				hash = (53 * hash) + getFriendsList().hashCode();
			}
			if (getSentFriendRequestsCount() > 0) {
				hash = (37 * hash) + SENT_FRIEND_REQUESTS_FIELD_NUMBER;
				hash = (53 * hash) + getSentFriendRequestsList().hashCode();
			}
			if (getReceivedFriendRequestsCount() > 0) {
				hash = (37 * hash) + RECEIVED_FRIEND_REQUESTS_FIELD_NUMBER;
				hash = (53 * hash) + getReceivedFriendRequestsList().hashCode();
			}
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(
				java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(
				java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}
		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}
		public static Builder newBuilder(net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}
		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		/**
		 * Protobuf type {@code gsync.player_api.FriendListV1.Response}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
				implements
					// @@protoc_insertion_point(builder_implements:gsync.player_api.FriendListV1.Response)
					net.averak.gsync.schema.protobuf.player_api.FriendListV1.ResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Response_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Response_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response.class,
								net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response.Builder.class);
			}

			// Construct using
			// net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response.newBuilder()
			private Builder() {

			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);

			}
			@java.lang.Override
			public Builder clear() {
				super.clear();
				bitField0_ = 0;
				if (friendsBuilder_ == null) {
					friends_ = java.util.Collections.emptyList();
				} else {
					friends_ = null;
					friendsBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000001);
				if (sentFriendRequestsBuilder_ == null) {
					sentFriendRequests_ = java.util.Collections.emptyList();
				} else {
					sentFriendRequests_ = null;
					sentFriendRequestsBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000002);
				if (receivedFriendRequestsBuilder_ == null) {
					receivedFriendRequests_ = java.util.Collections.emptyList();
				} else {
					receivedFriendRequests_ = null;
					receivedFriendRequestsBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_Response_descriptor;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response getDefaultInstanceForType() {
				return net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response.getDefaultInstance();
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response build() {
				net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response buildPartial() {
				net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response result = new net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response(
						this);
				buildPartialRepeatedFields(result);
				if (bitField0_ != 0) {
					buildPartial0(result);
				}
				onBuilt();
				return result;
			}

			private void buildPartialRepeatedFields(
					net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response result) {
				if (friendsBuilder_ == null) {
					if (((bitField0_ & 0x00000001) != 0)) {
						friends_ = java.util.Collections.unmodifiableList(friends_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.friends_ = friends_;
				} else {
					result.friends_ = friendsBuilder_.build();
				}
				if (sentFriendRequestsBuilder_ == null) {
					if (((bitField0_ & 0x00000002) != 0)) {
						sentFriendRequests_ = java.util.Collections.unmodifiableList(sentFriendRequests_);
						bitField0_ = (bitField0_ & ~0x00000002);
					}
					result.sentFriendRequests_ = sentFriendRequests_;
				} else {
					result.sentFriendRequests_ = sentFriendRequestsBuilder_.build();
				}
				if (receivedFriendRequestsBuilder_ == null) {
					if (((bitField0_ & 0x00000004) != 0)) {
						receivedFriendRequests_ = java.util.Collections.unmodifiableList(receivedFriendRequests_);
						bitField0_ = (bitField0_ & ~0x00000004);
					}
					result.receivedFriendRequests_ = receivedFriendRequests_;
				} else {
					result.receivedFriendRequests_ = receivedFriendRequestsBuilder_.build();
				}
			}

			private void buildPartial0(net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response result) {
				int from_bitField0_ = bitField0_;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}
			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}
			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}
			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}
			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}
			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}
			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response) {
					return mergeFrom((net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response other) {
				if (other == net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response.getDefaultInstance())
					return this;
				if (friendsBuilder_ == null) {
					if (!other.friends_.isEmpty()) {
						if (friends_.isEmpty()) {
							friends_ = other.friends_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureFriendsIsMutable();
							friends_.addAll(other.friends_);
						}
						onChanged();
					}
				} else {
					if (!other.friends_.isEmpty()) {
						if (friendsBuilder_.isEmpty()) {
							friendsBuilder_.dispose();
							friendsBuilder_ = null;
							friends_ = other.friends_;
							bitField0_ = (bitField0_ & ~0x00000001);
							friendsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? getFriendsFieldBuilder()
									: null;
						} else {
							friendsBuilder_.addAllMessages(other.friends_);
						}
					}
				}
				if (sentFriendRequestsBuilder_ == null) {
					if (!other.sentFriendRequests_.isEmpty()) {
						if (sentFriendRequests_.isEmpty()) {
							sentFriendRequests_ = other.sentFriendRequests_;
							bitField0_ = (bitField0_ & ~0x00000002);
						} else {
							ensureSentFriendRequestsIsMutable();
							sentFriendRequests_.addAll(other.sentFriendRequests_);
						}
						onChanged();
					}
				} else {
					if (!other.sentFriendRequests_.isEmpty()) {
						if (sentFriendRequestsBuilder_.isEmpty()) {
							sentFriendRequestsBuilder_.dispose();
							sentFriendRequestsBuilder_ = null;
							sentFriendRequests_ = other.sentFriendRequests_;
							bitField0_ = (bitField0_ & ~0x00000002);
							sentFriendRequestsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? getSentFriendRequestsFieldBuilder()
									: null;
						} else {
							sentFriendRequestsBuilder_.addAllMessages(other.sentFriendRequests_);
						}
					}
				}
				if (receivedFriendRequestsBuilder_ == null) {
					if (!other.receivedFriendRequests_.isEmpty()) {
						if (receivedFriendRequests_.isEmpty()) {
							receivedFriendRequests_ = other.receivedFriendRequests_;
							bitField0_ = (bitField0_ & ~0x00000004);
						} else {
							ensureReceivedFriendRequestsIsMutable();
							receivedFriendRequests_.addAll(other.receivedFriendRequests_);
						}
						onChanged();
					}
				} else {
					if (!other.receivedFriendRequests_.isEmpty()) {
						if (receivedFriendRequestsBuilder_.isEmpty()) {
							receivedFriendRequestsBuilder_.dispose();
							receivedFriendRequestsBuilder_ = null;
							receivedFriendRequests_ = other.receivedFriendRequests_;
							bitField0_ = (bitField0_ & ~0x00000004);
							receivedFriendRequestsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? getReceivedFriendRequestsFieldBuilder()
									: null;
						} else {
							receivedFriendRequestsBuilder_.addAllMessages(other.receivedFriendRequests_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0 :
								done = true;
								break;
							case 10 : {
								net.averak.gsync.schema.protobuf.resource.friend.Friend m = input.readMessage(
										net.averak.gsync.schema.protobuf.resource.friend.Friend.parser(),
										extensionRegistry);
								if (friendsBuilder_ == null) {
									ensureFriendsIsMutable();
									friends_.add(m);
								} else {
									friendsBuilder_.addMessage(m);
								}
								break;
							} // case 10
							case 18 : {
								net.averak.gsync.schema.protobuf.resource.friend.FriendRequest m = input.readMessage(
										net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.parser(),
										extensionRegistry);
								if (sentFriendRequestsBuilder_ == null) {
									ensureSentFriendRequestsIsMutable();
									sentFriendRequests_.add(m);
								} else {
									sentFriendRequestsBuilder_.addMessage(m);
								}
								break;
							} // case 18
							case 26 : {
								net.averak.gsync.schema.protobuf.resource.friend.FriendRequest m = input.readMessage(
										net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.parser(),
										extensionRegistry);
								if (receivedFriendRequestsBuilder_ == null) {
									ensureReceivedFriendRequestsIsMutable();
									receivedFriendRequests_.add(m);
								} else {
									receivedFriendRequestsBuilder_.addMessage(m);
								}
								break;
							} // case 26
							default : {
								if (!super.parseUnknownField(input, extensionRegistry, tag)) {
									done = true; // was an endgroup tag
								}
								break;
							} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}
			private int bitField0_;

			private java.util.List<net.averak.gsync.schema.protobuf.resource.friend.Friend> friends_ = java.util.Collections
					.emptyList();
			private void ensureFriendsIsMutable() {
				if (!((bitField0_ & 0x00000001) != 0)) {
					friends_ = new java.util.ArrayList<net.averak.gsync.schema.protobuf.resource.friend.Friend>(
							friends_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.Friend, net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder> friendsBuilder_;

			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.Friend> getFriendsList() {
				if (friendsBuilder_ == null) {
					return java.util.Collections.unmodifiableList(friends_);
				} else {
					return friendsBuilder_.getMessageList();
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public int getFriendsCount() {
				if (friendsBuilder_ == null) {
					return friends_.size();
				} else {
					return friendsBuilder_.getCount();
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.Friend getFriends(int index) {
				if (friendsBuilder_ == null) {
					return friends_.get(index);
				} else {
					return friendsBuilder_.getMessage(index);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder setFriends(int index, net.averak.gsync.schema.protobuf.resource.friend.Friend value) {
				if (friendsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureFriendsIsMutable();
					friends_.set(index, value);
					onChanged();
				} else {
					friendsBuilder_.setMessage(index, value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder setFriends(int index,
					net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder builderForValue) {
				if (friendsBuilder_ == null) {
					ensureFriendsIsMutable();
					friends_.set(index, builderForValue.build());
					onChanged();
				} else {
					friendsBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder addFriends(net.averak.gsync.schema.protobuf.resource.friend.Friend value) {
				if (friendsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureFriendsIsMutable();
					friends_.add(value);
					onChanged();
				} else {
					friendsBuilder_.addMessage(value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder addFriends(int index, net.averak.gsync.schema.protobuf.resource.friend.Friend value) {
				if (friendsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureFriendsIsMutable();
					friends_.add(index, value);
					onChanged();
				} else {
					friendsBuilder_.addMessage(index, value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder addFriends(net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder builderForValue) {
				if (friendsBuilder_ == null) {
					ensureFriendsIsMutable();
					friends_.add(builderForValue.build());
					onChanged();
				} else {
					friendsBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder addFriends(int index,
					net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder builderForValue) {
				if (friendsBuilder_ == null) {
					ensureFriendsIsMutable();
					friends_.add(index, builderForValue.build());
					onChanged();
				} else {
					friendsBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder addAllFriends(
					java.lang.Iterable<? extends net.averak.gsync.schema.protobuf.resource.friend.Friend> values) {
				if (friendsBuilder_ == null) {
					ensureFriendsIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, friends_);
					onChanged();
				} else {
					friendsBuilder_.addAllMessages(values);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder clearFriends() {
				if (friendsBuilder_ == null) {
					friends_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					friendsBuilder_.clear();
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public Builder removeFriends(int index) {
				if (friendsBuilder_ == null) {
					ensureFriendsIsMutable();
					friends_.remove(index);
					onChanged();
				} else {
					friendsBuilder_.remove(index);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder getFriendsBuilder(int index) {
				return getFriendsFieldBuilder().getBuilder(index);
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder getFriendsOrBuilder(int index) {
				if (friendsBuilder_ == null) {
					return friends_.get(index);
				} else {
					return friendsBuilder_.getMessageOrBuilder(index);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder> getFriendsOrBuilderList() {
				if (friendsBuilder_ != null) {
					return friendsBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(friends_);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder addFriendsBuilder() {
				return getFriendsFieldBuilder()
						.addBuilder(net.averak.gsync.schema.protobuf.resource.friend.Friend.getDefaultInstance());
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder addFriendsBuilder(int index) {
				return getFriendsFieldBuilder().addBuilder(index,
						net.averak.gsync.schema.protobuf.resource.friend.Friend.getDefaultInstance());
			}
			/**
			 * <code>repeated .gsync.resource.friend.Friend friends = 1;</code>
			 */
			public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder> getFriendsBuilderList() {
				return getFriendsFieldBuilder().getBuilderList();
			}
			private com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.Friend, net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder> getFriendsFieldBuilder() {
				if (friendsBuilder_ == null) {
					friendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.Friend, net.averak.gsync.schema.protobuf.resource.friend.Friend.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendOrBuilder>(
							friends_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
					friends_ = null;
				}
				return friendsBuilder_;
			}

			private java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> sentFriendRequests_ = java.util.Collections
					.emptyList();
			private void ensureSentFriendRequestsIsMutable() {
				if (!((bitField0_ & 0x00000002) != 0)) {
					sentFriendRequests_ = new java.util.ArrayList<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest>(
							sentFriendRequests_);
					bitField0_ |= 0x00000002;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest, net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> sentFriendRequestsBuilder_;

			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> getSentFriendRequestsList() {
				if (sentFriendRequestsBuilder_ == null) {
					return java.util.Collections.unmodifiableList(sentFriendRequests_);
				} else {
					return sentFriendRequestsBuilder_.getMessageList();
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public int getSentFriendRequestsCount() {
				if (sentFriendRequestsBuilder_ == null) {
					return sentFriendRequests_.size();
				} else {
					return sentFriendRequestsBuilder_.getCount();
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest getSentFriendRequests(int index) {
				if (sentFriendRequestsBuilder_ == null) {
					return sentFriendRequests_.get(index);
				} else {
					return sentFriendRequestsBuilder_.getMessage(index);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder setSentFriendRequests(int index,
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest value) {
				if (sentFriendRequestsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSentFriendRequestsIsMutable();
					sentFriendRequests_.set(index, value);
					onChanged();
				} else {
					sentFriendRequestsBuilder_.setMessage(index, value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder setSentFriendRequests(int index,
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder builderForValue) {
				if (sentFriendRequestsBuilder_ == null) {
					ensureSentFriendRequestsIsMutable();
					sentFriendRequests_.set(index, builderForValue.build());
					onChanged();
				} else {
					sentFriendRequestsBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder addSentFriendRequests(net.averak.gsync.schema.protobuf.resource.friend.FriendRequest value) {
				if (sentFriendRequestsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSentFriendRequestsIsMutable();
					sentFriendRequests_.add(value);
					onChanged();
				} else {
					sentFriendRequestsBuilder_.addMessage(value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder addSentFriendRequests(int index,
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest value) {
				if (sentFriendRequestsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSentFriendRequestsIsMutable();
					sentFriendRequests_.add(index, value);
					onChanged();
				} else {
					sentFriendRequestsBuilder_.addMessage(index, value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder addSentFriendRequests(
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder builderForValue) {
				if (sentFriendRequestsBuilder_ == null) {
					ensureSentFriendRequestsIsMutable();
					sentFriendRequests_.add(builderForValue.build());
					onChanged();
				} else {
					sentFriendRequestsBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder addSentFriendRequests(int index,
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder builderForValue) {
				if (sentFriendRequestsBuilder_ == null) {
					ensureSentFriendRequestsIsMutable();
					sentFriendRequests_.add(index, builderForValue.build());
					onChanged();
				} else {
					sentFriendRequestsBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder addAllSentFriendRequests(
					java.lang.Iterable<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> values) {
				if (sentFriendRequestsBuilder_ == null) {
					ensureSentFriendRequestsIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, sentFriendRequests_);
					onChanged();
				} else {
					sentFriendRequestsBuilder_.addAllMessages(values);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder clearSentFriendRequests() {
				if (sentFriendRequestsBuilder_ == null) {
					sentFriendRequests_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000002);
					onChanged();
				} else {
					sentFriendRequestsBuilder_.clear();
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public Builder removeSentFriendRequests(int index) {
				if (sentFriendRequestsBuilder_ == null) {
					ensureSentFriendRequestsIsMutable();
					sentFriendRequests_.remove(index);
					onChanged();
				} else {
					sentFriendRequestsBuilder_.remove(index);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder getSentFriendRequestsBuilder(
					int index) {
				return getSentFriendRequestsFieldBuilder().getBuilder(index);
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder getSentFriendRequestsOrBuilder(
					int index) {
				if (sentFriendRequestsBuilder_ == null) {
					return sentFriendRequests_.get(index);
				} else {
					return sentFriendRequestsBuilder_.getMessageOrBuilder(index);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> getSentFriendRequestsOrBuilderList() {
				if (sentFriendRequestsBuilder_ != null) {
					return sentFriendRequestsBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(sentFriendRequests_);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder addSentFriendRequestsBuilder() {
				return getSentFriendRequestsFieldBuilder().addBuilder(
						net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.getDefaultInstance());
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder addSentFriendRequestsBuilder(
					int index) {
				return getSentFriendRequestsFieldBuilder().addBuilder(index,
						net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.getDefaultInstance());
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest sent_friend_requests = 2;</code>
			 */
			public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder> getSentFriendRequestsBuilderList() {
				return getSentFriendRequestsFieldBuilder().getBuilderList();
			}
			private com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest, net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> getSentFriendRequestsFieldBuilder() {
				if (sentFriendRequestsBuilder_ == null) {
					sentFriendRequestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest, net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder>(
							sentFriendRequests_, ((bitField0_ & 0x00000002) != 0), getParentForChildren(), isClean());
					sentFriendRequests_ = null;
				}
				return sentFriendRequestsBuilder_;
			}

			private java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> receivedFriendRequests_ = java.util.Collections
					.emptyList();
			private void ensureReceivedFriendRequestsIsMutable() {
				if (!((bitField0_ & 0x00000004) != 0)) {
					receivedFriendRequests_ = new java.util.ArrayList<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest>(
							receivedFriendRequests_);
					bitField0_ |= 0x00000004;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest, net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> receivedFriendRequestsBuilder_;

			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> getReceivedFriendRequestsList() {
				if (receivedFriendRequestsBuilder_ == null) {
					return java.util.Collections.unmodifiableList(receivedFriendRequests_);
				} else {
					return receivedFriendRequestsBuilder_.getMessageList();
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public int getReceivedFriendRequestsCount() {
				if (receivedFriendRequestsBuilder_ == null) {
					return receivedFriendRequests_.size();
				} else {
					return receivedFriendRequestsBuilder_.getCount();
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest getReceivedFriendRequests(int index) {
				if (receivedFriendRequestsBuilder_ == null) {
					return receivedFriendRequests_.get(index);
				} else {
					return receivedFriendRequestsBuilder_.getMessage(index);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder setReceivedFriendRequests(int index,
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest value) {
				if (receivedFriendRequestsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureReceivedFriendRequestsIsMutable();
					receivedFriendRequests_.set(index, value);
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.setMessage(index, value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder setReceivedFriendRequests(int index,
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder builderForValue) {
				if (receivedFriendRequestsBuilder_ == null) {
					ensureReceivedFriendRequestsIsMutable();
					receivedFriendRequests_.set(index, builderForValue.build());
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder addReceivedFriendRequests(
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest value) {
				if (receivedFriendRequestsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureReceivedFriendRequestsIsMutable();
					receivedFriendRequests_.add(value);
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.addMessage(value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder addReceivedFriendRequests(int index,
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest value) {
				if (receivedFriendRequestsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureReceivedFriendRequestsIsMutable();
					receivedFriendRequests_.add(index, value);
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.addMessage(index, value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder addReceivedFriendRequests(
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder builderForValue) {
				if (receivedFriendRequestsBuilder_ == null) {
					ensureReceivedFriendRequestsIsMutable();
					receivedFriendRequests_.add(builderForValue.build());
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder addReceivedFriendRequests(int index,
					net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder builderForValue) {
				if (receivedFriendRequestsBuilder_ == null) {
					ensureReceivedFriendRequestsIsMutable();
					receivedFriendRequests_.add(index, builderForValue.build());
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder addAllReceivedFriendRequests(
					java.lang.Iterable<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendRequest> values) {
				if (receivedFriendRequestsBuilder_ == null) {
					ensureReceivedFriendRequestsIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, receivedFriendRequests_);
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.addAllMessages(values);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder clearReceivedFriendRequests() {
				if (receivedFriendRequestsBuilder_ == null) {
					receivedFriendRequests_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.clear();
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public Builder removeReceivedFriendRequests(int index) {
				if (receivedFriendRequestsBuilder_ == null) {
					ensureReceivedFriendRequestsIsMutable();
					receivedFriendRequests_.remove(index);
					onChanged();
				} else {
					receivedFriendRequestsBuilder_.remove(index);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder getReceivedFriendRequestsBuilder(
					int index) {
				return getReceivedFriendRequestsFieldBuilder().getBuilder(index);
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder getReceivedFriendRequestsOrBuilder(
					int index) {
				if (receivedFriendRequestsBuilder_ == null) {
					return receivedFriendRequests_.get(index);
				} else {
					return receivedFriendRequestsBuilder_.getMessageOrBuilder(index);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public java.util.List<? extends net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> getReceivedFriendRequestsOrBuilderList() {
				if (receivedFriendRequestsBuilder_ != null) {
					return receivedFriendRequestsBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(receivedFriendRequests_);
				}
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder addReceivedFriendRequestsBuilder() {
				return getReceivedFriendRequestsFieldBuilder().addBuilder(
						net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.getDefaultInstance());
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder addReceivedFriendRequestsBuilder(
					int index) {
				return getReceivedFriendRequestsFieldBuilder().addBuilder(index,
						net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.getDefaultInstance());
			}
			/**
			 * <code>repeated .gsync.resource.friend.FriendRequest received_friend_requests = 3;</code>
			 */
			public java.util.List<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder> getReceivedFriendRequestsBuilderList() {
				return getReceivedFriendRequestsFieldBuilder().getBuilderList();
			}
			private com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest, net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder> getReceivedFriendRequestsFieldBuilder() {
				if (receivedFriendRequestsBuilder_ == null) {
					receivedFriendRequestsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.friend.FriendRequest, net.averak.gsync.schema.protobuf.resource.friend.FriendRequest.Builder, net.averak.gsync.schema.protobuf.resource.friend.FriendRequestOrBuilder>(
							receivedFriendRequests_, ((bitField0_ & 0x00000004) != 0), getParentForChildren(),
							isClean());
					receivedFriendRequests_ = null;
				}
				return receivedFriendRequestsBuilder_;
			}
			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:gsync.player_api.FriendListV1.Response)
		}

		// @@protoc_insertion_point(class_scope:gsync.player_api.FriendListV1.Response)
		private static final net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response();
		}

		public static net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Response> PARSER = new com.google.protobuf.AbstractParser<Response>() {
			@java.lang.Override
			public Response parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
							.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		public static com.google.protobuf.Parser<Response> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Response> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.FriendListV1.Response getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private byte memoizedIsInitialized = -1;
	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		getUnknownFields().writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		size += getUnknownFields().getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.FriendListV1)) {
			return super.equals(obj);
		}
		net.averak.gsync.schema.protobuf.player_api.FriendListV1 other = (net.averak.gsync.schema.protobuf.player_api.FriendListV1) obj;

		if (!getUnknownFields().equals(other.getUnknownFields()))
			return false;
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (29 * hash) + getUnknownFields().hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(
			com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(
			com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseDelimitedFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(
			com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}
	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 parseFrom(
			com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}
	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}
	public static Builder newBuilder(net.averak.gsync.schema.protobuf.player_api.FriendListV1 prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}
	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}
	/**
	 * Protobuf type {@code gsync.player_api.FriendListV1}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
			implements
				// @@protoc_insertion_point(builder_implements:gsync.player_api.FriendListV1)
				net.averak.gsync.schema.protobuf.player_api.FriendListV1OrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_fieldAccessorTable
					.ensureFieldAccessorsInitialized(net.averak.gsync.schema.protobuf.player_api.FriendListV1.class,
							net.averak.gsync.schema.protobuf.player_api.FriendListV1.Builder.class);
		}

		// Construct using
		// net.averak.gsync.schema.protobuf.player_api.FriendListV1.newBuilder()
		private Builder() {

		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);

		}
		@java.lang.Override
		public Builder clear() {
			super.clear();
			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return net.averak.gsync.schema.protobuf.player_api.FriendOuterClass.internal_static_gsync_player_api_FriendListV1_descriptor;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.FriendListV1 getDefaultInstanceForType() {
			return net.averak.gsync.schema.protobuf.player_api.FriendListV1.getDefaultInstance();
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.FriendListV1 build() {
			net.averak.gsync.schema.protobuf.player_api.FriendListV1 result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.FriendListV1 buildPartial() {
			net.averak.gsync.schema.protobuf.player_api.FriendListV1 result = new net.averak.gsync.schema.protobuf.player_api.FriendListV1(
					this);
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}
		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}
		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}
		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}
		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}
		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}
		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof net.averak.gsync.schema.protobuf.player_api.FriendListV1) {
				return mergeFrom((net.averak.gsync.schema.protobuf.player_api.FriendListV1) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.FriendListV1 other) {
			if (other == net.averak.gsync.schema.protobuf.player_api.FriendListV1.getDefaultInstance())
				return this;
			this.mergeUnknownFields(other.getUnknownFields());
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0 :
							done = true;
							break;
						default : {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
					} // switch (tag)
				} // while (!done)
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.unwrapIOException();
			} finally {
				onChanged();
			} // finally
			return this;
		}
		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:gsync.player_api.FriendListV1)
	}

	// @@protoc_insertion_point(class_scope:gsync.player_api.FriendListV1)
	private static final net.averak.gsync.schema.protobuf.player_api.FriendListV1 DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.FriendListV1();
	}

	public static net.averak.gsync.schema.protobuf.player_api.FriendListV1 getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<FriendListV1> PARSER = new com.google.protobuf.AbstractParser<FriendListV1>() {
		@java.lang.Override
		public FriendListV1 parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			Builder builder = newBuilder();
			try {
				builder.mergeFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(builder.buildPartial());
			} catch (com.google.protobuf.UninitializedMessageException e) {
				throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
						.setUnfinishedMessage(builder.buildPartial());
			}
			return builder.buildPartial();
		}
	};

	public static com.google.protobuf.Parser<FriendListV1> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<FriendListV1> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public net.averak.gsync.schema.protobuf.player_api.FriendListV1 getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
