// Generated by protoc-gen-java-gsync-server. DO NOT EDIT!
// source: player_api/echo.proto
package net.averak.gsync.schema.protobuf.player_api;

import net.averak.gsync.infrastructure.grpc.player_api.Request;

import javax.annotation.Nonnull;

public interface IEchoHandler {
	@Nonnull
	EchoEchoV1.Response echoV1(@Nonnull Request<EchoEchoV1.Request> request);
}
