// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_api/player_storage.proto

// Protobuf Java Version: 3.25.1
package net.averak.gsync.schema.protobuf.player_api;

/**
 * Protobuf type {@code gsync.player_api.PlayerStorageSetV1}
 */
public final class PlayerStorageSetV1 extends com.google.protobuf.GeneratedMessageV3
		implements
			// @@protoc_insertion_point(message_implements:gsync.player_api.PlayerStorageSetV1)
			PlayerStorageSetV1OrBuilder {
	private static final long serialVersionUID = 0L;
	// Use PlayerStorageSetV1.newBuilder() to construct.
	private PlayerStorageSetV1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}
	private PlayerStorageSetV1() {
	}

	@java.lang.Override
	@SuppressWarnings({"unused"})
	protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
		return new PlayerStorageSetV1();
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_fieldAccessorTable
				.ensureFieldAccessorsInitialized(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.class,
						net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Builder.class);
	}

	public interface RequestOrBuilder
			extends
				// @@protoc_insertion_point(interface_extends:gsync.player_api.PlayerStorageSetV1.Request)
				com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 * 
		 * @return Whether the entry field is set.
		 */
		boolean hasEntry();
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 * 
		 * @return The entry.
		 */
		net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntry();
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntryOrBuilder();

		/**
		 * <code>string previous_revision = 2;</code>
		 * 
		 * @return The previousRevision.
		 */
		java.lang.String getPreviousRevision();
		/**
		 * <code>string previous_revision = 2;</code>
		 * 
		 * @return The bytes for previousRevision.
		 */
		com.google.protobuf.ByteString getPreviousRevisionBytes();
	}
	/**
	 * Protobuf type {@code gsync.player_api.PlayerStorageSetV1.Request}
	 */
	public static final class Request extends com.google.protobuf.GeneratedMessageV3
			implements
				// @@protoc_insertion_point(message_implements:gsync.player_api.PlayerStorageSetV1.Request)
				RequestOrBuilder {
		private static final long serialVersionUID = 0L;
		// Use Request.newBuilder() to construct.
		private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}
		private Request() {
			previousRevision_ = "";
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
			return new Request();
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Request_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Request_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request.class,
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request.Builder.class);
		}

		private int bitField0_;
		public static final int ENTRY_FIELD_NUMBER = 1;
		private net.averak.gsync.schema.protobuf.resource.player_storage.Entry entry_;
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 * 
		 * @return Whether the entry field is set.
		 */
		@java.lang.Override
		public boolean hasEntry() {
			return ((bitField0_ & 0x00000001) != 0);
		}
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 * 
		 * @return The entry.
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntry() {
			return entry_ == null
					? net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance()
					: entry_;
		}
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntryOrBuilder() {
			return entry_ == null
					? net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance()
					: entry_;
		}

		public static final int PREVIOUS_REVISION_FIELD_NUMBER = 2;
		@SuppressWarnings("serial")
		private volatile java.lang.Object previousRevision_ = "";
		/**
		 * <code>string previous_revision = 2;</code>
		 * 
		 * @return The previousRevision.
		 */
		@java.lang.Override
		public java.lang.String getPreviousRevision() {
			java.lang.Object ref = previousRevision_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				previousRevision_ = s;
				return s;
			}
		}
		/**
		 * <code>string previous_revision = 2;</code>
		 * 
		 * @return The bytes for previousRevision.
		 */
		@java.lang.Override
		public com.google.protobuf.ByteString getPreviousRevisionBytes() {
			java.lang.Object ref = previousRevision_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				previousRevision_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;
		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (((bitField0_ & 0x00000001) != 0)) {
				output.writeMessage(1, getEntry());
			}
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(previousRevision_)) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, previousRevision_);
			}
			getUnknownFields().writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) != 0)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getEntry());
			}
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(previousRevision_)) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, previousRevision_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request)) {
				return super.equals(obj);
			}
			net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request other = (net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request) obj;

			if (hasEntry() != other.hasEntry())
				return false;
			if (hasEntry()) {
				if (!getEntry().equals(other.getEntry()))
					return false;
			}
			if (!getPreviousRevision().equals(other.getPreviousRevision()))
				return false;
			if (!getUnknownFields().equals(other.getUnknownFields()))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (hasEntry()) {
				hash = (37 * hash) + ENTRY_FIELD_NUMBER;
				hash = (53 * hash) + getEntry().hashCode();
			}
			hash = (37 * hash) + PREVIOUS_REVISION_FIELD_NUMBER;
			hash = (53 * hash) + getPreviousRevision().hashCode();
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(
				java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(
				java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}
		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}
		public static Builder newBuilder(
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}
		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		/**
		 * Protobuf type {@code gsync.player_api.PlayerStorageSetV1.Request}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
				implements
					// @@protoc_insertion_point(builder_implements:gsync.player_api.PlayerStorageSetV1.Request)
					net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.RequestOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Request_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Request_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request.class,
								net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request.Builder.class);
			}

			// Construct using
			// net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}
			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					getEntryFieldBuilder();
				}
			}
			@java.lang.Override
			public Builder clear() {
				super.clear();
				bitField0_ = 0;
				entry_ = null;
				if (entryBuilder_ != null) {
					entryBuilder_.dispose();
					entryBuilder_ = null;
				}
				previousRevision_ = "";
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Request_descriptor;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request getDefaultInstanceForType() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request.getDefaultInstance();
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request build() {
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request buildPartial() {
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request result = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request(
						this);
				if (bitField0_ != 0) {
					buildPartial0(result);
				}
				onBuilt();
				return result;
			}

			private void buildPartial0(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request result) {
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) != 0)) {
					result.entry_ = entryBuilder_ == null ? entry_ : entryBuilder_.build();
					to_bitField0_ |= 0x00000001;
				}
				if (((from_bitField0_ & 0x00000002) != 0)) {
					result.previousRevision_ = previousRevision_;
				}
				result.bitField0_ |= to_bitField0_;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}
			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}
			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}
			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}
			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}
			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}
			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request) {
					return mergeFrom((net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request other) {
				if (other == net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request
						.getDefaultInstance())
					return this;
				if (other.hasEntry()) {
					mergeEntry(other.getEntry());
				}
				if (!other.getPreviousRevision().isEmpty()) {
					previousRevision_ = other.previousRevision_;
					bitField0_ |= 0x00000002;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0 :
								done = true;
								break;
							case 10 : {
								input.readMessage(getEntryFieldBuilder().getBuilder(), extensionRegistry);
								bitField0_ |= 0x00000001;
								break;
							} // case 10
							case 18 : {
								previousRevision_ = input.readStringRequireUtf8();
								bitField0_ |= 0x00000002;
								break;
							} // case 18
							default : {
								if (!super.parseUnknownField(input, extensionRegistry, tag)) {
									done = true; // was an endgroup tag
								}
								break;
							} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}
			private int bitField0_;

			private net.averak.gsync.schema.protobuf.resource.player_storage.Entry entry_;
			private com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> entryBuilder_;
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 * 
			 * @return Whether the entry field is set.
			 */
			public boolean hasEntry() {
				return ((bitField0_ & 0x00000001) != 0);
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 * 
			 * @return The entry.
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntry() {
				if (entryBuilder_ == null) {
					return entry_ == null
							? net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance()
							: entry_;
				} else {
					return entryBuilder_.getMessage();
				}
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public Builder setEntry(net.averak.gsync.schema.protobuf.resource.player_storage.Entry value) {
				if (entryBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					entry_ = value;
				} else {
					entryBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public Builder setEntry(
					net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder builderForValue) {
				if (entryBuilder_ == null) {
					entry_ = builderForValue.build();
				} else {
					entryBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public Builder mergeEntry(net.averak.gsync.schema.protobuf.resource.player_storage.Entry value) {
				if (entryBuilder_ == null) {
					if (((bitField0_ & 0x00000001) != 0) && entry_ != null
							&& entry_ != net.averak.gsync.schema.protobuf.resource.player_storage.Entry
									.getDefaultInstance()) {
						getEntryBuilder().mergeFrom(value);
					} else {
						entry_ = value;
					}
				} else {
					entryBuilder_.mergeFrom(value);
				}
				if (entry_ != null) {
					bitField0_ |= 0x00000001;
					onChanged();
				}
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public Builder clearEntry() {
				bitField0_ = (bitField0_ & ~0x00000001);
				entry_ = null;
				if (entryBuilder_ != null) {
					entryBuilder_.dispose();
					entryBuilder_ = null;
				}
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder getEntryBuilder() {
				bitField0_ |= 0x00000001;
				onChanged();
				return getEntryFieldBuilder().getBuilder();
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntryOrBuilder() {
				if (entryBuilder_ != null) {
					return entryBuilder_.getMessageOrBuilder();
				} else {
					return entry_ == null
							? net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance()
							: entry_;
				}
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			private com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> getEntryFieldBuilder() {
				if (entryBuilder_ == null) {
					entryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder>(
							getEntry(), getParentForChildren(), isClean());
					entry_ = null;
				}
				return entryBuilder_;
			}

			private java.lang.Object previousRevision_ = "";
			/**
			 * <code>string previous_revision = 2;</code>
			 * 
			 * @return The previousRevision.
			 */
			public java.lang.String getPreviousRevision() {
				java.lang.Object ref = previousRevision_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					previousRevision_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>string previous_revision = 2;</code>
			 * 
			 * @return The bytes for previousRevision.
			 */
			public com.google.protobuf.ByteString getPreviousRevisionBytes() {
				java.lang.Object ref = previousRevision_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					previousRevision_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>string previous_revision = 2;</code>
			 * 
			 * @param value
			 *            The previousRevision to set.
			 * @return This builder for chaining.
			 */
			public Builder setPreviousRevision(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				previousRevision_ = value;
				bitField0_ |= 0x00000002;
				onChanged();
				return this;
			}
			/**
			 * <code>string previous_revision = 2;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearPreviousRevision() {
				previousRevision_ = getDefaultInstance().getPreviousRevision();
				bitField0_ = (bitField0_ & ~0x00000002);
				onChanged();
				return this;
			}
			/**
			 * <code>string previous_revision = 2;</code>
			 * 
			 * @param value
			 *            The bytes for previousRevision to set.
			 * @return This builder for chaining.
			 */
			public Builder setPreviousRevisionBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				previousRevision_ = value;
				bitField0_ |= 0x00000002;
				onChanged();
				return this;
			}
			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:gsync.player_api.PlayerStorageSetV1.Request)
		}

		// @@protoc_insertion_point(class_scope:gsync.player_api.PlayerStorageSetV1.Request)
		private static final net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request();
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Request> PARSER = new com.google.protobuf.AbstractParser<Request>() {
			@java.lang.Override
			public Request parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
							.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		public static com.google.protobuf.Parser<Request> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Request> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Request getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface ResponseOrBuilder
			extends
				// @@protoc_insertion_point(interface_extends:gsync.player_api.PlayerStorageSetV1.Response)
				com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 * 
		 * @return Whether the entry field is set.
		 */
		boolean hasEntry();
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 * 
		 * @return The entry.
		 */
		net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntry();
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntryOrBuilder();

		/**
		 * <code>string next_revision = 2;</code>
		 * 
		 * @return The nextRevision.
		 */
		java.lang.String getNextRevision();
		/**
		 * <code>string next_revision = 2;</code>
		 * 
		 * @return The bytes for nextRevision.
		 */
		com.google.protobuf.ByteString getNextRevisionBytes();
	}
	/**
	 * Protobuf type {@code gsync.player_api.PlayerStorageSetV1.Response}
	 */
	public static final class Response extends com.google.protobuf.GeneratedMessageV3
			implements
				// @@protoc_insertion_point(message_implements:gsync.player_api.PlayerStorageSetV1.Response)
				ResponseOrBuilder {
		private static final long serialVersionUID = 0L;
		// Use Response.newBuilder() to construct.
		private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}
		private Response() {
			nextRevision_ = "";
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
			return new Response();
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Response_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Response_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response.class,
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response.Builder.class);
		}

		private int bitField0_;
		public static final int ENTRY_FIELD_NUMBER = 1;
		private net.averak.gsync.schema.protobuf.resource.player_storage.Entry entry_;
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 * 
		 * @return Whether the entry field is set.
		 */
		@java.lang.Override
		public boolean hasEntry() {
			return ((bitField0_ & 0x00000001) != 0);
		}
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 * 
		 * @return The entry.
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntry() {
			return entry_ == null
					? net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance()
					: entry_;
		}
		/**
		 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntryOrBuilder() {
			return entry_ == null
					? net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance()
					: entry_;
		}

		public static final int NEXT_REVISION_FIELD_NUMBER = 2;
		@SuppressWarnings("serial")
		private volatile java.lang.Object nextRevision_ = "";
		/**
		 * <code>string next_revision = 2;</code>
		 * 
		 * @return The nextRevision.
		 */
		@java.lang.Override
		public java.lang.String getNextRevision() {
			java.lang.Object ref = nextRevision_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				nextRevision_ = s;
				return s;
			}
		}
		/**
		 * <code>string next_revision = 2;</code>
		 * 
		 * @return The bytes for nextRevision.
		 */
		@java.lang.Override
		public com.google.protobuf.ByteString getNextRevisionBytes() {
			java.lang.Object ref = nextRevision_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				nextRevision_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;
		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (((bitField0_ & 0x00000001) != 0)) {
				output.writeMessage(1, getEntry());
			}
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nextRevision_)) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nextRevision_);
			}
			getUnknownFields().writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) != 0)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getEntry());
			}
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nextRevision_)) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nextRevision_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response)) {
				return super.equals(obj);
			}
			net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response other = (net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response) obj;

			if (hasEntry() != other.hasEntry())
				return false;
			if (hasEntry()) {
				if (!getEntry().equals(other.getEntry()))
					return false;
			}
			if (!getNextRevision().equals(other.getNextRevision()))
				return false;
			if (!getUnknownFields().equals(other.getUnknownFields()))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (hasEntry()) {
				hash = (37 * hash) + ENTRY_FIELD_NUMBER;
				hash = (53 * hash) + getEntry().hashCode();
			}
			hash = (37 * hash) + NEXT_REVISION_FIELD_NUMBER;
			hash = (53 * hash) + getNextRevision().hashCode();
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(
				java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(
				java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}
		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}
		public static Builder newBuilder(
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}
		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		/**
		 * Protobuf type {@code gsync.player_api.PlayerStorageSetV1.Response}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
				implements
					// @@protoc_insertion_point(builder_implements:gsync.player_api.PlayerStorageSetV1.Response)
					net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.ResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Response_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Response_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response.class,
								net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response.Builder.class);
			}

			// Construct using
			// net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}
			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					getEntryFieldBuilder();
				}
			}
			@java.lang.Override
			public Builder clear() {
				super.clear();
				bitField0_ = 0;
				entry_ = null;
				if (entryBuilder_ != null) {
					entryBuilder_.dispose();
					entryBuilder_ = null;
				}
				nextRevision_ = "";
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_Response_descriptor;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response getDefaultInstanceForType() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response.getDefaultInstance();
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response build() {
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response buildPartial() {
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response result = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response(
						this);
				if (bitField0_ != 0) {
					buildPartial0(result);
				}
				onBuilt();
				return result;
			}

			private void buildPartial0(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response result) {
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) != 0)) {
					result.entry_ = entryBuilder_ == null ? entry_ : entryBuilder_.build();
					to_bitField0_ |= 0x00000001;
				}
				if (((from_bitField0_ & 0x00000002) != 0)) {
					result.nextRevision_ = nextRevision_;
				}
				result.bitField0_ |= to_bitField0_;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}
			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}
			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}
			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}
			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}
			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}
			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response) {
					return mergeFrom((net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response other) {
				if (other == net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response
						.getDefaultInstance())
					return this;
				if (other.hasEntry()) {
					mergeEntry(other.getEntry());
				}
				if (!other.getNextRevision().isEmpty()) {
					nextRevision_ = other.nextRevision_;
					bitField0_ |= 0x00000002;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0 :
								done = true;
								break;
							case 10 : {
								input.readMessage(getEntryFieldBuilder().getBuilder(), extensionRegistry);
								bitField0_ |= 0x00000001;
								break;
							} // case 10
							case 18 : {
								nextRevision_ = input.readStringRequireUtf8();
								bitField0_ |= 0x00000002;
								break;
							} // case 18
							default : {
								if (!super.parseUnknownField(input, extensionRegistry, tag)) {
									done = true; // was an endgroup tag
								}
								break;
							} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}
			private int bitField0_;

			private net.averak.gsync.schema.protobuf.resource.player_storage.Entry entry_;
			private com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> entryBuilder_;
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 * 
			 * @return Whether the entry field is set.
			 */
			public boolean hasEntry() {
				return ((bitField0_ & 0x00000001) != 0);
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 * 
			 * @return The entry.
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntry() {
				if (entryBuilder_ == null) {
					return entry_ == null
							? net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance()
							: entry_;
				} else {
					return entryBuilder_.getMessage();
				}
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public Builder setEntry(net.averak.gsync.schema.protobuf.resource.player_storage.Entry value) {
				if (entryBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					entry_ = value;
				} else {
					entryBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public Builder setEntry(
					net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder builderForValue) {
				if (entryBuilder_ == null) {
					entry_ = builderForValue.build();
				} else {
					entryBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public Builder mergeEntry(net.averak.gsync.schema.protobuf.resource.player_storage.Entry value) {
				if (entryBuilder_ == null) {
					if (((bitField0_ & 0x00000001) != 0) && entry_ != null
							&& entry_ != net.averak.gsync.schema.protobuf.resource.player_storage.Entry
									.getDefaultInstance()) {
						getEntryBuilder().mergeFrom(value);
					} else {
						entry_ = value;
					}
				} else {
					entryBuilder_.mergeFrom(value);
				}
				if (entry_ != null) {
					bitField0_ |= 0x00000001;
					onChanged();
				}
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public Builder clearEntry() {
				bitField0_ = (bitField0_ & ~0x00000001);
				entry_ = null;
				if (entryBuilder_ != null) {
					entryBuilder_.dispose();
					entryBuilder_ = null;
				}
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder getEntryBuilder() {
				bitField0_ |= 0x00000001;
				onChanged();
				return getEntryFieldBuilder().getBuilder();
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntryOrBuilder() {
				if (entryBuilder_ != null) {
					return entryBuilder_.getMessageOrBuilder();
				} else {
					return entry_ == null
							? net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance()
							: entry_;
				}
			}
			/**
			 * <code>.gsync.resource.player_storage.Entry entry = 1;</code>
			 */
			private com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> getEntryFieldBuilder() {
				if (entryBuilder_ == null) {
					entryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder>(
							getEntry(), getParentForChildren(), isClean());
					entry_ = null;
				}
				return entryBuilder_;
			}

			private java.lang.Object nextRevision_ = "";
			/**
			 * <code>string next_revision = 2;</code>
			 * 
			 * @return The nextRevision.
			 */
			public java.lang.String getNextRevision() {
				java.lang.Object ref = nextRevision_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					nextRevision_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}
			/**
			 * <code>string next_revision = 2;</code>
			 * 
			 * @return The bytes for nextRevision.
			 */
			public com.google.protobuf.ByteString getNextRevisionBytes() {
				java.lang.Object ref = nextRevision_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					nextRevision_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}
			/**
			 * <code>string next_revision = 2;</code>
			 * 
			 * @param value
			 *            The nextRevision to set.
			 * @return This builder for chaining.
			 */
			public Builder setNextRevision(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				nextRevision_ = value;
				bitField0_ |= 0x00000002;
				onChanged();
				return this;
			}
			/**
			 * <code>string next_revision = 2;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearNextRevision() {
				nextRevision_ = getDefaultInstance().getNextRevision();
				bitField0_ = (bitField0_ & ~0x00000002);
				onChanged();
				return this;
			}
			/**
			 * <code>string next_revision = 2;</code>
			 * 
			 * @param value
			 *            The bytes for nextRevision to set.
			 * @return This builder for chaining.
			 */
			public Builder setNextRevisionBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				nextRevision_ = value;
				bitField0_ |= 0x00000002;
				onChanged();
				return this;
			}
			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:gsync.player_api.PlayerStorageSetV1.Response)
		}

		// @@protoc_insertion_point(class_scope:gsync.player_api.PlayerStorageSetV1.Response)
		private static final net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response();
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Response> PARSER = new com.google.protobuf.AbstractParser<Response>() {
			@java.lang.Override
			public Response parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
							.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		public static com.google.protobuf.Parser<Response> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Response> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Response getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private byte memoizedIsInitialized = -1;
	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		getUnknownFields().writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		size += getUnknownFields().getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1)) {
			return super.equals(obj);
		}
		net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 other = (net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1) obj;

		if (!getUnknownFields().equals(other.getUnknownFields()))
			return false;
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (29 * hash) + getUnknownFields().hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(
			com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(
			com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseDelimitedFrom(
			java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseDelimitedFrom(
			java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(
			com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 parseFrom(
			com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}
	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}
	public static Builder newBuilder(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}
	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}
	/**
	 * Protobuf type {@code gsync.player_api.PlayerStorageSetV1}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
			implements
				// @@protoc_insertion_point(builder_implements:gsync.player_api.PlayerStorageSetV1)
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1OrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.class,
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.Builder.class);
		}

		// Construct using
		// net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.newBuilder()
		private Builder() {

		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);

		}
		@java.lang.Override
		public Builder clear() {
			super.clear();
			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSetV1_descriptor;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 getDefaultInstanceForType() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.getDefaultInstance();
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 build() {
			net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 buildPartial() {
			net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 result = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1(
					this);
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}
		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}
		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}
		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}
		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}
		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}
		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1) {
				return mergeFrom((net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 other) {
			if (other == net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1.getDefaultInstance())
				return this;
			this.mergeUnknownFields(other.getUnknownFields());
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0 :
							done = true;
							break;
						default : {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
					} // switch (tag)
				} // while (!done)
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.unwrapIOException();
			} finally {
				onChanged();
			} // finally
			return this;
		}
		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:gsync.player_api.PlayerStorageSetV1)
	}

	// @@protoc_insertion_point(class_scope:gsync.player_api.PlayerStorageSetV1)
	private static final net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1();
	}

	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<PlayerStorageSetV1> PARSER = new com.google.protobuf.AbstractParser<PlayerStorageSetV1>() {
		@java.lang.Override
		public PlayerStorageSetV1 parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			Builder builder = newBuilder();
			try {
				builder.mergeFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(builder.buildPartial());
			} catch (com.google.protobuf.UninitializedMessageException e) {
				throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
						.setUnfinishedMessage(builder.buildPartial());
			}
			return builder.buildPartial();
		}
	};

	public static com.google.protobuf.Parser<PlayerStorageSetV1> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<PlayerStorageSetV1> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSetV1 getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
