// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_api/player_storage.proto

// Protobuf Java Version: 3.25.1
package net.averak.gsync.schema.protobuf.player_api;

public interface PlayerStorageSearchV1OrBuilder
		extends
			// @@protoc_insertion_point(interface_extends:gsync.player_api.PlayerStorageSearchV1)
			com.google.protobuf.MessageOrBuilder {
}
