// Generated by protoc-gen-java-gsync-server. DO NOT EDIT!
// source: player_api/player_storage.proto
package net.averak.gsync.schema.protobuf.player_api;

import io.grpc.stub.StreamObserver;
import net.averak.gsync.infrastructure.grpc.player_api.HandlerWrapper;
import net.averak.gsync.infrastructure.grpc.player_api.Request;
import org.springframework.stereotype.Component;

@Component
public class PlayerStorageHandlerWrapper extends PlayerStorageGrpc.PlayerStorageImplBase {
	private final HandlerWrapper handlerWrapper;
	private final IPlayerStorageHandler handler;

	public PlayerStorageHandlerWrapper(HandlerWrapper handlerWrapper, IPlayerStorageHandler handler) {
		this.handlerWrapper = handlerWrapper;
		this.handler = handler;
	}

	@Override
	public void searchV1(PlayerStorageSearchV1.Request request,
			StreamObserver<PlayerStorageSearchV1.Response> responseObserver) {
		handlerWrapper.invoke(handler::searchV1, request, responseObserver);
	}

	@Override
	public void setV1(PlayerStorageSetV1.Request request,
			StreamObserver<PlayerStorageSetV1.Response> responseObserver) {
		handlerWrapper.invoke(handler::setV1, request, responseObserver);
	}

	@Override
	public void clearV1(PlayerStorageClearV1.Request request,
			StreamObserver<PlayerStorageClearV1.Response> responseObserver) {
		handlerWrapper.invoke(handler::clearV1, request, responseObserver);
	}

}
