// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_api/player_storage.proto

// Protobuf Java Version: 3.25.1
package net.averak.gsync.schema.protobuf.player_api;

/**
 * Protobuf type {@code gsync.player_api.PlayerStorageSearchV1}
 */
public final class PlayerStorageSearchV1 extends com.google.protobuf.GeneratedMessageV3
		implements
			// @@protoc_insertion_point(message_implements:gsync.player_api.PlayerStorageSearchV1)
			PlayerStorageSearchV1OrBuilder {
	private static final long serialVersionUID = 0L;
	// Use PlayerStorageSearchV1.newBuilder() to construct.
	private PlayerStorageSearchV1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}
	private PlayerStorageSearchV1() {
	}

	@java.lang.Override
	@SuppressWarnings({"unused"})
	protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
		return new PlayerStorageSearchV1();
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
						net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.class,
						net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Builder.class);
	}

	public interface RequestOrBuilder
			extends
				// @@protoc_insertion_point(interface_extends:gsync.player_api.PlayerStorageSearchV1.Request)
				com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
		 * 
		 * @return Whether the criteria field is set.
		 */
		boolean hasCriteria();
		/**
		 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
		 * 
		 * @return The criteria.
		 */
		net.averak.gsync.schema.protobuf.resource.player_storage.Criteria getCriteria();
		/**
		 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.player_storage.CriteriaOrBuilder getCriteriaOrBuilder();
	}
	/**
	 * Protobuf type {@code gsync.player_api.PlayerStorageSearchV1.Request}
	 */
	public static final class Request extends com.google.protobuf.GeneratedMessageV3
			implements
				// @@protoc_insertion_point(message_implements:gsync.player_api.PlayerStorageSearchV1.Request)
				RequestOrBuilder {
		private static final long serialVersionUID = 0L;
		// Use Request.newBuilder() to construct.
		private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}
		private Request() {
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
			return new Request();
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Request_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Request_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request.class,
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request.Builder.class);
		}

		private int bitField0_;
		public static final int CRITERIA_FIELD_NUMBER = 1;
		private net.averak.gsync.schema.protobuf.resource.player_storage.Criteria criteria_;
		/**
		 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
		 * 
		 * @return Whether the criteria field is set.
		 */
		@java.lang.Override
		public boolean hasCriteria() {
			return ((bitField0_ & 0x00000001) != 0);
		}
		/**
		 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
		 * 
		 * @return The criteria.
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.player_storage.Criteria getCriteria() {
			return criteria_ == null
					? net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.getDefaultInstance()
					: criteria_;
		}
		/**
		 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.player_storage.CriteriaOrBuilder getCriteriaOrBuilder() {
			return criteria_ == null
					? net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.getDefaultInstance()
					: criteria_;
		}

		private byte memoizedIsInitialized = -1;
		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (((bitField0_ & 0x00000001) != 0)) {
				output.writeMessage(1, getCriteria());
			}
			getUnknownFields().writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) != 0)) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getCriteria());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request)) {
				return super.equals(obj);
			}
			net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request other = (net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request) obj;

			if (hasCriteria() != other.hasCriteria())
				return false;
			if (hasCriteria()) {
				if (!getCriteria().equals(other.getCriteria()))
					return false;
			}
			if (!getUnknownFields().equals(other.getUnknownFields()))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (hasCriteria()) {
				hash = (37 * hash) + CRITERIA_FIELD_NUMBER;
				hash = (53 * hash) + getCriteria().hashCode();
			}
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(
				java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(
				java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}
		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}
		public static Builder newBuilder(
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}
		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		/**
		 * Protobuf type {@code gsync.player_api.PlayerStorageSearchV1.Request}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
				implements
					// @@protoc_insertion_point(builder_implements:gsync.player_api.PlayerStorageSearchV1.Request)
					net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.RequestOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Request_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Request_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request.class,
								net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request.Builder.class);
			}

			// Construct using
			// net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}
			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					getCriteriaFieldBuilder();
				}
			}
			@java.lang.Override
			public Builder clear() {
				super.clear();
				bitField0_ = 0;
				criteria_ = null;
				if (criteriaBuilder_ != null) {
					criteriaBuilder_.dispose();
					criteriaBuilder_ = null;
				}
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Request_descriptor;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request getDefaultInstanceForType() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request.getDefaultInstance();
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request build() {
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request buildPartial() {
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request result = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request(
						this);
				if (bitField0_ != 0) {
					buildPartial0(result);
				}
				onBuilt();
				return result;
			}

			private void buildPartial0(
					net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request result) {
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) != 0)) {
					result.criteria_ = criteriaBuilder_ == null ? criteria_ : criteriaBuilder_.build();
					to_bitField0_ |= 0x00000001;
				}
				result.bitField0_ |= to_bitField0_;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}
			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}
			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}
			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}
			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}
			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}
			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request) {
					return mergeFrom((net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request other) {
				if (other == net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request
						.getDefaultInstance())
					return this;
				if (other.hasCriteria()) {
					mergeCriteria(other.getCriteria());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0 :
								done = true;
								break;
							case 10 : {
								input.readMessage(getCriteriaFieldBuilder().getBuilder(), extensionRegistry);
								bitField0_ |= 0x00000001;
								break;
							} // case 10
							default : {
								if (!super.parseUnknownField(input, extensionRegistry, tag)) {
									done = true; // was an endgroup tag
								}
								break;
							} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}
			private int bitField0_;

			private net.averak.gsync.schema.protobuf.resource.player_storage.Criteria criteria_;
			private com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Criteria, net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.CriteriaOrBuilder> criteriaBuilder_;
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 * 
			 * @return Whether the criteria field is set.
			 */
			public boolean hasCriteria() {
				return ((bitField0_ & 0x00000001) != 0);
			}
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 * 
			 * @return The criteria.
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Criteria getCriteria() {
				if (criteriaBuilder_ == null) {
					return criteria_ == null
							? net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.getDefaultInstance()
							: criteria_;
				} else {
					return criteriaBuilder_.getMessage();
				}
			}
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 */
			public Builder setCriteria(net.averak.gsync.schema.protobuf.resource.player_storage.Criteria value) {
				if (criteriaBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					criteria_ = value;
				} else {
					criteriaBuilder_.setMessage(value);
				}
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 */
			public Builder setCriteria(
					net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.Builder builderForValue) {
				if (criteriaBuilder_ == null) {
					criteria_ = builderForValue.build();
				} else {
					criteriaBuilder_.setMessage(builderForValue.build());
				}
				bitField0_ |= 0x00000001;
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 */
			public Builder mergeCriteria(net.averak.gsync.schema.protobuf.resource.player_storage.Criteria value) {
				if (criteriaBuilder_ == null) {
					if (((bitField0_ & 0x00000001) != 0) && criteria_ != null
							&& criteria_ != net.averak.gsync.schema.protobuf.resource.player_storage.Criteria
									.getDefaultInstance()) {
						getCriteriaBuilder().mergeFrom(value);
					} else {
						criteria_ = value;
					}
				} else {
					criteriaBuilder_.mergeFrom(value);
				}
				if (criteria_ != null) {
					bitField0_ |= 0x00000001;
					onChanged();
				}
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 */
			public Builder clearCriteria() {
				bitField0_ = (bitField0_ & ~0x00000001);
				criteria_ = null;
				if (criteriaBuilder_ != null) {
					criteriaBuilder_.dispose();
					criteriaBuilder_ = null;
				}
				onChanged();
				return this;
			}
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.Builder getCriteriaBuilder() {
				bitField0_ |= 0x00000001;
				onChanged();
				return getCriteriaFieldBuilder().getBuilder();
			}
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.CriteriaOrBuilder getCriteriaOrBuilder() {
				if (criteriaBuilder_ != null) {
					return criteriaBuilder_.getMessageOrBuilder();
				} else {
					return criteria_ == null
							? net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.getDefaultInstance()
							: criteria_;
				}
			}
			/**
			 * <code>.gsync.resource.player_storage.Criteria criteria = 1;</code>
			 */
			private com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Criteria, net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.CriteriaOrBuilder> getCriteriaFieldBuilder() {
				if (criteriaBuilder_ == null) {
					criteriaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Criteria, net.averak.gsync.schema.protobuf.resource.player_storage.Criteria.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.CriteriaOrBuilder>(
							getCriteria(), getParentForChildren(), isClean());
					criteria_ = null;
				}
				return criteriaBuilder_;
			}
			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:gsync.player_api.PlayerStorageSearchV1.Request)
		}

		// @@protoc_insertion_point(class_scope:gsync.player_api.PlayerStorageSearchV1.Request)
		private static final net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request();
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Request> PARSER = new com.google.protobuf.AbstractParser<Request>() {
			@java.lang.Override
			public Request parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
							.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		public static com.google.protobuf.Parser<Request> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Request> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Request getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface ResponseOrBuilder
			extends
				// @@protoc_insertion_point(interface_extends:gsync.player_api.PlayerStorageSearchV1.Response)
				com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		java.util.List<net.averak.gsync.schema.protobuf.resource.player_storage.Entry> getEntriesList();
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntries(int index);
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		int getEntriesCount();
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		java.util.List<? extends net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> getEntriesOrBuilderList();
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntriesOrBuilder(int index);
	}
	/**
	 * Protobuf type {@code gsync.player_api.PlayerStorageSearchV1.Response}
	 */
	public static final class Response extends com.google.protobuf.GeneratedMessageV3
			implements
				// @@protoc_insertion_point(message_implements:gsync.player_api.PlayerStorageSearchV1.Response)
				ResponseOrBuilder {
		private static final long serialVersionUID = 0L;
		// Use Response.newBuilder() to construct.
		private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}
		private Response() {
			entries_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
			return new Response();
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Response_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Response_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response.class,
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response.Builder.class);
		}

		public static final int ENTRIES_FIELD_NUMBER = 1;
		@SuppressWarnings("serial")
		private java.util.List<net.averak.gsync.schema.protobuf.resource.player_storage.Entry> entries_;
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		@java.lang.Override
		public java.util.List<net.averak.gsync.schema.protobuf.resource.player_storage.Entry> getEntriesList() {
			return entries_;
		}
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		@java.lang.Override
		public java.util.List<? extends net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> getEntriesOrBuilderList() {
			return entries_;
		}
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		@java.lang.Override
		public int getEntriesCount() {
			return entries_.size();
		}
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntries(int index) {
			return entries_.get(index);
		}
		/**
		 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
		 */
		@java.lang.Override
		public net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntriesOrBuilder(int index) {
			return entries_.get(index);
		}

		private byte memoizedIsInitialized = -1;
		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			for (int i = 0; i < entries_.size(); i++) {
				output.writeMessage(1, entries_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < entries_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, entries_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response)) {
				return super.equals(obj);
			}
			net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response other = (net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response) obj;

			if (!getEntriesList().equals(other.getEntriesList()))
				return false;
			if (!getUnknownFields().equals(other.getUnknownFields()))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (getEntriesCount() > 0) {
				hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
				hash = (53 * hash) + getEntriesList().hashCode();
			}
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(
				java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(
				java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(
				com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(
				com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseDelimitedFrom(
				java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}
		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response parseFrom(
				com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}
		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}
		public static Builder newBuilder(
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}
		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}
		/**
		 * Protobuf type {@code gsync.player_api.PlayerStorageSearchV1.Response}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
				implements
					// @@protoc_insertion_point(builder_implements:gsync.player_api.PlayerStorageSearchV1.Response)
					net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.ResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Response_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Response_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response.class,
								net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response.Builder.class);
			}

			// Construct using
			// net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response.newBuilder()
			private Builder() {

			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);

			}
			@java.lang.Override
			public Builder clear() {
				super.clear();
				bitField0_ = 0;
				if (entriesBuilder_ == null) {
					entries_ = java.util.Collections.emptyList();
				} else {
					entries_ = null;
					entriesBuilder_.clear();
				}
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_Response_descriptor;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response getDefaultInstanceForType() {
				return net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response.getDefaultInstance();
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response build() {
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response buildPartial() {
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response result = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response(
						this);
				buildPartialRepeatedFields(result);
				if (bitField0_ != 0) {
					buildPartial0(result);
				}
				onBuilt();
				return result;
			}

			private void buildPartialRepeatedFields(
					net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response result) {
				if (entriesBuilder_ == null) {
					if (((bitField0_ & 0x00000001) != 0)) {
						entries_ = java.util.Collections.unmodifiableList(entries_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.entries_ = entries_;
				} else {
					result.entries_ = entriesBuilder_.build();
				}
			}

			private void buildPartial0(
					net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response result) {
				int from_bitField0_ = bitField0_;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}
			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}
			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}
			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}
			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}
			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}
			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response) {
					return mergeFrom(
							(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response other) {
				if (other == net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response
						.getDefaultInstance())
					return this;
				if (entriesBuilder_ == null) {
					if (!other.entries_.isEmpty()) {
						if (entries_.isEmpty()) {
							entries_ = other.entries_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureEntriesIsMutable();
							entries_.addAll(other.entries_);
						}
						onChanged();
					}
				} else {
					if (!other.entries_.isEmpty()) {
						if (entriesBuilder_.isEmpty()) {
							entriesBuilder_.dispose();
							entriesBuilder_ = null;
							entries_ = other.entries_;
							bitField0_ = (bitField0_ & ~0x00000001);
							entriesBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? getEntriesFieldBuilder()
									: null;
						} else {
							entriesBuilder_.addAllMessages(other.entries_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
							case 0 :
								done = true;
								break;
							case 10 : {
								net.averak.gsync.schema.protobuf.resource.player_storage.Entry m = input.readMessage(
										net.averak.gsync.schema.protobuf.resource.player_storage.Entry.parser(),
										extensionRegistry);
								if (entriesBuilder_ == null) {
									ensureEntriesIsMutable();
									entries_.add(m);
								} else {
									entriesBuilder_.addMessage(m);
								}
								break;
							} // case 10
							default : {
								if (!super.parseUnknownField(input, extensionRegistry, tag)) {
									done = true; // was an endgroup tag
								}
								break;
							} // default:
						} // switch (tag)
					} // while (!done)
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.unwrapIOException();
				} finally {
					onChanged();
				} // finally
				return this;
			}
			private int bitField0_;

			private java.util.List<net.averak.gsync.schema.protobuf.resource.player_storage.Entry> entries_ = java.util.Collections
					.emptyList();
			private void ensureEntriesIsMutable() {
				if (!((bitField0_ & 0x00000001) != 0)) {
					entries_ = new java.util.ArrayList<net.averak.gsync.schema.protobuf.resource.player_storage.Entry>(
							entries_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> entriesBuilder_;

			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public java.util.List<net.averak.gsync.schema.protobuf.resource.player_storage.Entry> getEntriesList() {
				if (entriesBuilder_ == null) {
					return java.util.Collections.unmodifiableList(entries_);
				} else {
					return entriesBuilder_.getMessageList();
				}
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public int getEntriesCount() {
				if (entriesBuilder_ == null) {
					return entries_.size();
				} else {
					return entriesBuilder_.getCount();
				}
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Entry getEntries(int index) {
				if (entriesBuilder_ == null) {
					return entries_.get(index);
				} else {
					return entriesBuilder_.getMessage(index);
				}
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder setEntries(int index, net.averak.gsync.schema.protobuf.resource.player_storage.Entry value) {
				if (entriesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureEntriesIsMutable();
					entries_.set(index, value);
					onChanged();
				} else {
					entriesBuilder_.setMessage(index, value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder setEntries(int index,
					net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder builderForValue) {
				if (entriesBuilder_ == null) {
					ensureEntriesIsMutable();
					entries_.set(index, builderForValue.build());
					onChanged();
				} else {
					entriesBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder addEntries(net.averak.gsync.schema.protobuf.resource.player_storage.Entry value) {
				if (entriesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureEntriesIsMutable();
					entries_.add(value);
					onChanged();
				} else {
					entriesBuilder_.addMessage(value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder addEntries(int index, net.averak.gsync.schema.protobuf.resource.player_storage.Entry value) {
				if (entriesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureEntriesIsMutable();
					entries_.add(index, value);
					onChanged();
				} else {
					entriesBuilder_.addMessage(index, value);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder addEntries(
					net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder builderForValue) {
				if (entriesBuilder_ == null) {
					ensureEntriesIsMutable();
					entries_.add(builderForValue.build());
					onChanged();
				} else {
					entriesBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder addEntries(int index,
					net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder builderForValue) {
				if (entriesBuilder_ == null) {
					ensureEntriesIsMutable();
					entries_.add(index, builderForValue.build());
					onChanged();
				} else {
					entriesBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder addAllEntries(
					java.lang.Iterable<? extends net.averak.gsync.schema.protobuf.resource.player_storage.Entry> values) {
				if (entriesBuilder_ == null) {
					ensureEntriesIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, entries_);
					onChanged();
				} else {
					entriesBuilder_.addAllMessages(values);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder clearEntries() {
				if (entriesBuilder_ == null) {
					entries_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					entriesBuilder_.clear();
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public Builder removeEntries(int index) {
				if (entriesBuilder_ == null) {
					ensureEntriesIsMutable();
					entries_.remove(index);
					onChanged();
				} else {
					entriesBuilder_.remove(index);
				}
				return this;
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder getEntriesBuilder(int index) {
				return getEntriesFieldBuilder().getBuilder(index);
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder getEntriesOrBuilder(
					int index) {
				if (entriesBuilder_ == null) {
					return entries_.get(index);
				} else {
					return entriesBuilder_.getMessageOrBuilder(index);
				}
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public java.util.List<? extends net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> getEntriesOrBuilderList() {
				if (entriesBuilder_ != null) {
					return entriesBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(entries_);
				}
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder addEntriesBuilder() {
				return getEntriesFieldBuilder().addBuilder(
						net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance());
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder addEntriesBuilder(int index) {
				return getEntriesFieldBuilder().addBuilder(index,
						net.averak.gsync.schema.protobuf.resource.player_storage.Entry.getDefaultInstance());
			}
			/**
			 * <code>repeated .gsync.resource.player_storage.Entry entries = 1;</code>
			 */
			public java.util.List<net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder> getEntriesBuilderList() {
				return getEntriesFieldBuilder().getBuilderList();
			}
			private com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder> getEntriesFieldBuilder() {
				if (entriesBuilder_ == null) {
					entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<net.averak.gsync.schema.protobuf.resource.player_storage.Entry, net.averak.gsync.schema.protobuf.resource.player_storage.Entry.Builder, net.averak.gsync.schema.protobuf.resource.player_storage.EntryOrBuilder>(
							entries_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
					entries_ = null;
				}
				return entriesBuilder_;
			}
			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:gsync.player_api.PlayerStorageSearchV1.Response)
		}

		// @@protoc_insertion_point(class_scope:gsync.player_api.PlayerStorageSearchV1.Response)
		private static final net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response();
		}

		public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Response> PARSER = new com.google.protobuf.AbstractParser<Response>() {
			@java.lang.Override
			public Response parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				Builder builder = newBuilder();
				try {
					builder.mergeFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(builder.buildPartial());
				} catch (com.google.protobuf.UninitializedMessageException e) {
					throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e)
							.setUnfinishedMessage(builder.buildPartial());
				}
				return builder.buildPartial();
			}
		};

		public static com.google.protobuf.Parser<Response> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Response> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Response getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private byte memoizedIsInitialized = -1;
	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		getUnknownFields().writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		size += getUnknownFields().getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1)) {
			return super.equals(obj);
		}
		net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 other = (net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1) obj;

		if (!getUnknownFields().equals(other.getUnknownFields()))
			return false;
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (29 * hash) + getUnknownFields().hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(
			com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(
			com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseDelimitedFrom(
			java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseDelimitedFrom(
			java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(
			com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}
	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 parseFrom(
			com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}
	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}
	public static Builder newBuilder(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}
	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}
	/**
	 * Protobuf type {@code gsync.player_api.PlayerStorageSearchV1}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
			implements
				// @@protoc_insertion_point(builder_implements:gsync.player_api.PlayerStorageSearchV1)
				net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1OrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.class,
							net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.Builder.class);
		}

		// Construct using
		// net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.newBuilder()
		private Builder() {

		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);

		}
		@java.lang.Override
		public Builder clear() {
			super.clear();
			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageOuterClass.internal_static_gsync_player_api_PlayerStorageSearchV1_descriptor;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 getDefaultInstanceForType() {
			return net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.getDefaultInstance();
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 build() {
			net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 buildPartial() {
			net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 result = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1(
					this);
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}
		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}
		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}
		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}
		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}
		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}
		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1) {
				return mergeFrom((net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 other) {
			if (other == net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1.getDefaultInstance())
				return this;
			this.mergeUnknownFields(other.getUnknownFields());
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0 :
							done = true;
							break;
						default : {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
					} // switch (tag)
				} // while (!done)
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.unwrapIOException();
			} finally {
				onChanged();
			} // finally
			return this;
		}
		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:gsync.player_api.PlayerStorageSearchV1)
	}

	// @@protoc_insertion_point(class_scope:gsync.player_api.PlayerStorageSearchV1)
	private static final net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1();
	}

	public static net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<PlayerStorageSearchV1> PARSER = new com.google.protobuf.AbstractParser<PlayerStorageSearchV1>() {
		@java.lang.Override
		public PlayerStorageSearchV1 parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			Builder builder = newBuilder();
			try {
				builder.mergeFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(builder.buildPartial());
			} catch (com.google.protobuf.UninitializedMessageException e) {
				throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
						.setUnfinishedMessage(builder.buildPartial());
			}
			return builder.buildPartial();
		}
	};

	public static com.google.protobuf.Parser<PlayerStorageSearchV1> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<PlayerStorageSearchV1> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public net.averak.gsync.schema.protobuf.player_api.PlayerStorageSearchV1 getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

}
