quarkus:
  application:
    name: "gsync"
    version: "1.0.0-SNAPSHOT"
  log:
    console:
      json: true
  google:
    cloud:
      project-id: ${GOOGLE_CLOUD_PROJECT_ID:gsync}
      instance-id: ${GOOGLE_CLOUD_SPANNER_INSTANCE_ID:gsync}
      database-id: ${GOOGLE_CLOUD_SPANNER_DATABASE_NAME:gsync}
      spanner:
        emulator-host: http://localhost:9020

"%dev":
  quarkus:
    log:
      console:
        json: false

"%test":
  quarkus:
    log:
      console:
        json: false
