// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: custom_option.proto

// Protobuf Java Version: 3.25.2
package net.averak.gsync.schema.protobuf.custom_option;

public interface PlayerApiMethodOptionOrBuilder
		extends
			// @@protoc_insertion_point(interface_extends:gsync.custom_option.PlayerApiMethodOption)
			com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>repeated .gsync.custom_option.PlayerApiMethodOption.MethodErrorDefinition method_error_definitions = 1;</code>
	 */
	java.util.List<net.averak.gsync.schema.protobuf.custom_option.PlayerApiMethodOption.MethodErrorDefinition> getMethodErrorDefinitionsList();
	/**
	 * <code>repeated .gsync.custom_option.PlayerApiMethodOption.MethodErrorDefinition method_error_definitions = 1;</code>
	 */
	net.averak.gsync.schema.protobuf.custom_option.PlayerApiMethodOption.MethodErrorDefinition getMethodErrorDefinitions(
			int index);
	/**
	 * <code>repeated .gsync.custom_option.PlayerApiMethodOption.MethodErrorDefinition method_error_definitions = 1;</code>
	 */
	int getMethodErrorDefinitionsCount();
	/**
	 * <code>repeated .gsync.custom_option.PlayerApiMethodOption.MethodErrorDefinition method_error_definitions = 1;</code>
	 */
	java.util.List<? extends net.averak.gsync.schema.protobuf.custom_option.PlayerApiMethodOption.MethodErrorDefinitionOrBuilder> getMethodErrorDefinitionsOrBuilderList();
	/**
	 * <code>repeated .gsync.custom_option.PlayerApiMethodOption.MethodErrorDefinition method_error_definitions = 1;</code>
	 */
	net.averak.gsync.schema.protobuf.custom_option.PlayerApiMethodOption.MethodErrorDefinitionOrBuilder getMethodErrorDefinitionsOrBuilder(
			int index);
}
