[versions]
easy-random = "6.2.1"
groovy = "4.0.7"
kotlin = "1.9.20"
quarkus = "3.5.0"
spock = "2.4-M1-groovy-4.0"

[libraries]
commons-lang3 = "org.apache.commons:commons-lang3:3.13.0"
easy-random = { module = "io.github.dvgaba:easy-random-core", version.ref = "easy-random" }
groovy = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovy-sql = { module = "org.apache.groovy:groovy-sql", version.ref = "groovy" }
guava = "com.google.guava:guava:32.1.3-jre"
jackson-module-kotlin = "com.fasterxml.jackson.module:jackson-module-kotlin:2.16.0-rc1"
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
quarkus-arc = { module = "io.quarkus:quarkus-arc", version.ref = "quarkus" }
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-config-yaml = { module = "io.quarkus:quarkus-config-yaml", version.ref = "quarkus" }
quarkus-google-cloud-spanner = "io.quarkiverse.googlecloudservices:quarkus-google-cloud-spanner:2.6.0"
quarkus-hibernate-orm = { module = "io.quarkus:quarkus-hibernate-orm", version.ref = "quarkus" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5", version.ref = "quarkus" }
quarkus-kotlin = { module = "io.quarkus:quarkus-kotlin", version.ref = "quarkus" }
quarkus-logging-json = { module = "io.quarkus:quarkus-logging-json", version.ref = "quarkus" }
quarkus-resteasy-reactive = { module = "io.quarkus:quarkus-resteasy-reactive", version.ref = "quarkus" }
quarkus-resteasy-reactive-jackson = { module = "io.quarkus:quarkus-resteasy-reactive-jackson", version.ref = "quarkus" }
spock-core = { module = "org.spockframework:spock-core", version.ref = "spock" }

[plugins]
gradle-git-properties = "com.gorylenko.gradle-git-properties:2.4.1"
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
sonarqube = "org.sonarqube:4.4.1.3373"
spotless = "com.diffplug.spotless:6.22.0"
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.1"
versions = "com.github.ben-manes.versions:0.49.0"
