package net.averak.gsync.mybatis

import org.mybatis.generator.api.IntrospectedTable
import org.mybatis.generator.api.PluginAdapter
import org.mybatis.generator.api.dom.xml.Document
import org.mybatis.generator.api.dom.xml.TextElement
import org.mybatis.generator.api.dom.xml.XmlElement

/**
 * マスターデータをローカルキャッシュするプラグイン
 *
 */
class MasterDataCachePlugin : PluginAdapter() {

    override fun validate(warnings: List<String>): Boolean {
        return true
    }

    override fun sqlMapDocumentGenerated(document: Document, introspectedTable: IntrospectedTable): Boolean {
        val isMasterData = introspectedTable.allColumns.any { it.actualColumnName == "master_version" }
        if (isMasterData) {
            // <cache> element を追加すると、グローバルに参照可能なL2キャッシュが有効になる
            // デフォルトではトランザクション内に閉じたキャッシュのみ有効であるが、マスターデータは他トランザクションでもキャッシュを効かせる必要がある
            val element = XmlElement("cache")
            element.addElement(TextElement("<!--"))
            element.addElement(TextElement("  WARNING - @mbg.generated"))
            element.addElement(TextElement("  This element is generated by MasterDataCachePlugin."))
            element.addElement(TextElement("-->"))
            document.rootElement.addElement(element)
        }
        return super.sqlMapDocumentGenerated(document, introspectedTable)
    }
}
