// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_api/error/error_code.proto

// Protobuf Java Version: 3.25.2
package net.averak.gsync.schema.protobuf.player_api.error;

/**
 * Protobuf type {@code gsync.player_api.error.ErrorCode}
 */
public final class ErrorCode extends com.google.protobuf.GeneratedMessageV3
		implements
			// @@protoc_insertion_point(message_implements:gsync.player_api.error.ErrorCode)
			ErrorCodeOrBuilder {
	private static final long serialVersionUID = 0L;
	// Use ErrorCode.newBuilder() to construct.
	private ErrorCode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
		super(builder);
	}
	private ErrorCode() {
	}

	@java.lang.Override
	@SuppressWarnings({"unused"})
	protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
		return new ErrorCode();
	}

	public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
		return net.averak.gsync.schema.protobuf.player_api.error.ErrorCodeOuterClass.internal_static_gsync_player_api_error_ErrorCode_descriptor;
	}

	@java.lang.Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
		return net.averak.gsync.schema.protobuf.player_api.error.ErrorCodeOuterClass.internal_static_gsync_player_api_error_ErrorCode_fieldAccessorTable
				.ensureFieldAccessorsInitialized(net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.class,
						net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.Builder.class);
	}

	/**
	 * Protobuf enum {@code gsync.player_api.error.ErrorCode.Common}
	 */
	public enum Common implements com.google.protobuf.ProtocolMessageEnum {
		/**
		 * <code>COMMON_UNSPECIFIED = 0;</code>
		 */
		COMMON_UNSPECIFIED(0),
		/**
		 * <code>INVALID_SESSION = 1001 [(.gsync.player_api.error.ErrorCode.handling_type) = FATAL];</code>
		 */
		INVALID_SESSION(1001),
		/**
		 * <code>INVALID_CLIENT = 1002 [(.gsync.player_api.error.ErrorCode.handling_type) = FATAL];</code>
		 */
		INVALID_CLIENT(1002), UNRECOGNIZED(-1),;

		/**
		 * <code>COMMON_UNSPECIFIED = 0;</code>
		 */
		public static final int COMMON_UNSPECIFIED_VALUE = 0;
		/**
		 * <code>INVALID_SESSION = 1001 [(.gsync.player_api.error.ErrorCode.handling_type) = FATAL];</code>
		 */
		public static final int INVALID_SESSION_VALUE = 1001;
		/**
		 * <code>INVALID_CLIENT = 1002 [(.gsync.player_api.error.ErrorCode.handling_type) = FATAL];</code>
		 */
		public static final int INVALID_CLIENT_VALUE = 1002;

		public final int getNumber() {
			if (this == UNRECOGNIZED) {
				throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
			}
			return value;
		}

		/**
		 * @param value
		 *            The numeric wire value of the corresponding enum entry.
		 * @return The enum associated with the given numeric wire value.
		 * @deprecated Use {@link #forNumber(int)} instead.
		 */
		@java.lang.Deprecated
		public static Common valueOf(int value) {
			return forNumber(value);
		}

		/**
		 * @param value
		 *            The numeric wire value of the corresponding enum entry.
		 * @return The enum associated with the given numeric wire value.
		 */
		public static Common forNumber(int value) {
			switch (value) {
				case 0 :
					return COMMON_UNSPECIFIED;
				case 1001 :
					return INVALID_SESSION;
				case 1002 :
					return INVALID_CLIENT;
				default :
					return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<Common> internalGetValueMap() {
			return internalValueMap;
		}
		private static final com.google.protobuf.Internal.EnumLiteMap<Common> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Common>() {
			public Common findValueByNumber(int number) {
				return Common.forNumber(number);
			}
		};

		public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
			if (this == UNRECOGNIZED) {
				throw new java.lang.IllegalStateException("Can't get the descriptor of an unrecognized enum value.");
			}
			return getDescriptor().getValues().get(ordinal());
		}
		public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
			return getDescriptor();
		}
		public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.getDescriptor().getEnumTypes().get(0);
		}

		private static final Common[] VALUES = values();

		public static Common valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
			if (desc.getType() != getDescriptor()) {
				throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
			}
			if (desc.getIndex() == -1) {
				return UNRECOGNIZED;
			}
			return VALUES[desc.getIndex()];
		}

		private final int value;

		private Common(int value) {
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:gsync.player_api.error.ErrorCode.Common)
	}

	/**
	 * Protobuf enum {@code gsync.player_api.error.ErrorCode.Method}
	 */
	public enum Method implements com.google.protobuf.ProtocolMessageEnum {
		/**
		 * <code>METHOD_UNSPECIFIED = 0;</code>
		 */
		METHOD_UNSPECIFIED(0),
		/**
		 * <code>ILLEGAL_ARGUMENT = 2001 [(.gsync.player_api.error.ErrorCode.handling_type) = FATAL];</code>
		 */
		ILLEGAL_ARGUMENT(2001),
		/**
		 * <code>RESOURCE_NOT_FOUND = 2002 [(.gsync.player_api.error.ErrorCode.handling_type) = RECOVERABLE];</code>
		 */
		RESOURCE_NOT_FOUND(2002),
		/**
		 * <code>RESOURCE_CONFLICT = 2003 [(.gsync.player_api.error.ErrorCode.handling_type) = RECOVERABLE];</code>
		 */
		RESOURCE_CONFLICT(2003),
		/**
		 * <code>RESOURCE_INSUFFICIENT = 2004 [(.gsync.player_api.error.ErrorCode.handling_type) = RECOVERABLE];</code>
		 */
		RESOURCE_INSUFFICIENT(2004), UNRECOGNIZED(-1),;

		/**
		 * <code>METHOD_UNSPECIFIED = 0;</code>
		 */
		public static final int METHOD_UNSPECIFIED_VALUE = 0;
		/**
		 * <code>ILLEGAL_ARGUMENT = 2001 [(.gsync.player_api.error.ErrorCode.handling_type) = FATAL];</code>
		 */
		public static final int ILLEGAL_ARGUMENT_VALUE = 2001;
		/**
		 * <code>RESOURCE_NOT_FOUND = 2002 [(.gsync.player_api.error.ErrorCode.handling_type) = RECOVERABLE];</code>
		 */
		public static final int RESOURCE_NOT_FOUND_VALUE = 2002;
		/**
		 * <code>RESOURCE_CONFLICT = 2003 [(.gsync.player_api.error.ErrorCode.handling_type) = RECOVERABLE];</code>
		 */
		public static final int RESOURCE_CONFLICT_VALUE = 2003;
		/**
		 * <code>RESOURCE_INSUFFICIENT = 2004 [(.gsync.player_api.error.ErrorCode.handling_type) = RECOVERABLE];</code>
		 */
		public static final int RESOURCE_INSUFFICIENT_VALUE = 2004;

		public final int getNumber() {
			if (this == UNRECOGNIZED) {
				throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
			}
			return value;
		}

		/**
		 * @param value
		 *            The numeric wire value of the corresponding enum entry.
		 * @return The enum associated with the given numeric wire value.
		 * @deprecated Use {@link #forNumber(int)} instead.
		 */
		@java.lang.Deprecated
		public static Method valueOf(int value) {
			return forNumber(value);
		}

		/**
		 * @param value
		 *            The numeric wire value of the corresponding enum entry.
		 * @return The enum associated with the given numeric wire value.
		 */
		public static Method forNumber(int value) {
			switch (value) {
				case 0 :
					return METHOD_UNSPECIFIED;
				case 2001 :
					return ILLEGAL_ARGUMENT;
				case 2002 :
					return RESOURCE_NOT_FOUND;
				case 2003 :
					return RESOURCE_CONFLICT;
				case 2004 :
					return RESOURCE_INSUFFICIENT;
				default :
					return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<Method> internalGetValueMap() {
			return internalValueMap;
		}
		private static final com.google.protobuf.Internal.EnumLiteMap<Method> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<Method>() {
			public Method findValueByNumber(int number) {
				return Method.forNumber(number);
			}
		};

		public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
			if (this == UNRECOGNIZED) {
				throw new java.lang.IllegalStateException("Can't get the descriptor of an unrecognized enum value.");
			}
			return getDescriptor().getValues().get(ordinal());
		}
		public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
			return getDescriptor();
		}
		public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.getDescriptor().getEnumTypes().get(1);
		}

		private static final Method[] VALUES = values();

		public static Method valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
			if (desc.getType() != getDescriptor()) {
				throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
			}
			if (desc.getIndex() == -1) {
				return UNRECOGNIZED;
			}
			return VALUES[desc.getIndex()];
		}

		private final int value;

		private Method(int value) {
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:gsync.player_api.error.ErrorCode.Method)
	}

	/**
	 * Protobuf enum {@code gsync.player_api.error.ErrorCode.HandlingType}
	 */
	public enum HandlingType implements com.google.protobuf.ProtocolMessageEnum {
		/**
		 * <code>HANDLING_TYPE_UNSPECIFIED = 0;</code>
		 */
		HANDLING_TYPE_UNSPECIFIED(0),
		/**
		 * <pre>
		 * サバクラ間の前提条件が満たされていない場合に発生する致命的なエラー。
		 * 緊急メンテナンスで修正しなければならない。
		 * </pre>
		 *
		 * <code>FATAL = 1;</code>
		 */
		FATAL(1),
		/**
		 * <pre>
		 * サーバ側の一時的な不具合により発生したエラー。
		 * リトライすることにより解決する可能性がある。
		 * </pre>
		 *
		 * <code>TEMPORARY = 2;</code>
		 */
		TEMPORARY(2),
		/**
		 * <pre>
		 * クライアント側の不具合により発生したエラー。
		 * 1つ前の画面に遷移したりタイトルに戻して前提条件を変えることにより、解決する可能性がある。
		 * </pre>
		 *
		 * <code>RECOVERABLE = 3;</code>
		 */
		RECOVERABLE(3), UNRECOGNIZED(-1),;

		/**
		 * <code>HANDLING_TYPE_UNSPECIFIED = 0;</code>
		 */
		public static final int HANDLING_TYPE_UNSPECIFIED_VALUE = 0;
		/**
		 * <pre>
		 * サバクラ間の前提条件が満たされていない場合に発生する致命的なエラー。
		 * 緊急メンテナンスで修正しなければならない。
		 * </pre>
		 *
		 * <code>FATAL = 1;</code>
		 */
		public static final int FATAL_VALUE = 1;
		/**
		 * <pre>
		 * サーバ側の一時的な不具合により発生したエラー。
		 * リトライすることにより解決する可能性がある。
		 * </pre>
		 *
		 * <code>TEMPORARY = 2;</code>
		 */
		public static final int TEMPORARY_VALUE = 2;
		/**
		 * <pre>
		 * クライアント側の不具合により発生したエラー。
		 * 1つ前の画面に遷移したりタイトルに戻して前提条件を変えることにより、解決する可能性がある。
		 * </pre>
		 *
		 * <code>RECOVERABLE = 3;</code>
		 */
		public static final int RECOVERABLE_VALUE = 3;

		public final int getNumber() {
			if (this == UNRECOGNIZED) {
				throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
			}
			return value;
		}

		/**
		 * @param value
		 *            The numeric wire value of the corresponding enum entry.
		 * @return The enum associated with the given numeric wire value.
		 * @deprecated Use {@link #forNumber(int)} instead.
		 */
		@java.lang.Deprecated
		public static HandlingType valueOf(int value) {
			return forNumber(value);
		}

		/**
		 * @param value
		 *            The numeric wire value of the corresponding enum entry.
		 * @return The enum associated with the given numeric wire value.
		 */
		public static HandlingType forNumber(int value) {
			switch (value) {
				case 0 :
					return HANDLING_TYPE_UNSPECIFIED;
				case 1 :
					return FATAL;
				case 2 :
					return TEMPORARY;
				case 3 :
					return RECOVERABLE;
				default :
					return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<HandlingType> internalGetValueMap() {
			return internalValueMap;
		}
		private static final com.google.protobuf.Internal.EnumLiteMap<HandlingType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<HandlingType>() {
			public HandlingType findValueByNumber(int number) {
				return HandlingType.forNumber(number);
			}
		};

		public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
			if (this == UNRECOGNIZED) {
				throw new java.lang.IllegalStateException("Can't get the descriptor of an unrecognized enum value.");
			}
			return getDescriptor().getValues().get(ordinal());
		}
		public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
			return getDescriptor();
		}
		public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.getDescriptor().getEnumTypes().get(2);
		}

		private static final HandlingType[] VALUES = values();

		public static HandlingType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
			if (desc.getType() != getDescriptor()) {
				throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
			}
			if (desc.getIndex() == -1) {
				return UNRECOGNIZED;
			}
			return VALUES[desc.getIndex()];
		}

		private final int value;

		private HandlingType(int value) {
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:gsync.player_api.error.ErrorCode.HandlingType)
	}

	private byte memoizedIsInitialized = -1;
	@java.lang.Override
	public final boolean isInitialized() {
		byte isInitialized = memoizedIsInitialized;
		if (isInitialized == 1)
			return true;
		if (isInitialized == 0)
			return false;

		memoizedIsInitialized = 1;
		return true;
	}

	@java.lang.Override
	public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
		getUnknownFields().writeTo(output);
	}

	@java.lang.Override
	public int getSerializedSize() {
		int size = memoizedSize;
		if (size != -1)
			return size;

		size = 0;
		size += getUnknownFields().getSerializedSize();
		memoizedSize = size;
		return size;
	}

	@java.lang.Override
	public boolean equals(final java.lang.Object obj) {
		if (obj == this) {
			return true;
		}
		if (!(obj instanceof net.averak.gsync.schema.protobuf.player_api.error.ErrorCode)) {
			return super.equals(obj);
		}
		net.averak.gsync.schema.protobuf.player_api.error.ErrorCode other = (net.averak.gsync.schema.protobuf.player_api.error.ErrorCode) obj;

		if (!getUnknownFields().equals(other.getUnknownFields()))
			return false;
		return true;
	}

	@java.lang.Override
	public int hashCode() {
		if (memoizedHashCode != 0) {
			return memoizedHashCode;
		}
		int hash = 41;
		hash = (19 * hash) + getDescriptor().hashCode();
		hash = (29 * hash) + getUnknownFields().hashCode();
		memoizedHashCode = hash;
		return hash;
	}

	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(
			com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(
			com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
		return PARSER.parseFrom(data, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(java.io.InputStream input)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseDelimitedFrom(
			java.io.InputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
	}

	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseDelimitedFrom(
			java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(
			com.google.protobuf.CodedInputStream input) throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
	}
	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode parseFrom(
			com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
		return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
	}

	@java.lang.Override
	public Builder newBuilderForType() {
		return newBuilder();
	}
	public static Builder newBuilder() {
		return DEFAULT_INSTANCE.toBuilder();
	}
	public static Builder newBuilder(net.averak.gsync.schema.protobuf.player_api.error.ErrorCode prototype) {
		return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
	}
	@java.lang.Override
	public Builder toBuilder() {
		return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
	}

	@java.lang.Override
	protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
		Builder builder = new Builder(parent);
		return builder;
	}
	/**
	 * Protobuf type {@code gsync.player_api.error.ErrorCode}
	 */
	public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
			implements
				// @@protoc_insertion_point(builder_implements:gsync.player_api.error.ErrorCode)
				net.averak.gsync.schema.protobuf.player_api.error.ErrorCodeOrBuilder {
		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return net.averak.gsync.schema.protobuf.player_api.error.ErrorCodeOuterClass.internal_static_gsync_player_api_error_ErrorCode_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return net.averak.gsync.schema.protobuf.player_api.error.ErrorCodeOuterClass.internal_static_gsync_player_api_error_ErrorCode_fieldAccessorTable
					.ensureFieldAccessorsInitialized(net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.class,
							net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.Builder.class);
		}

		// Construct using
		// net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.newBuilder()
		private Builder() {

		}

		private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			super(parent);

		}
		@java.lang.Override
		public Builder clear() {
			super.clear();
			return this;
		}

		@java.lang.Override
		public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
			return net.averak.gsync.schema.protobuf.player_api.error.ErrorCodeOuterClass.internal_static_gsync_player_api_error_ErrorCode_descriptor;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.error.ErrorCode getDefaultInstanceForType() {
			return net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.getDefaultInstance();
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.error.ErrorCode build() {
			net.averak.gsync.schema.protobuf.player_api.error.ErrorCode result = buildPartial();
			if (!result.isInitialized()) {
				throw newUninitializedMessageException(result);
			}
			return result;
		}

		@java.lang.Override
		public net.averak.gsync.schema.protobuf.player_api.error.ErrorCode buildPartial() {
			net.averak.gsync.schema.protobuf.player_api.error.ErrorCode result = new net.averak.gsync.schema.protobuf.player_api.error.ErrorCode(
					this);
			onBuilt();
			return result;
		}

		@java.lang.Override
		public Builder clone() {
			return super.clone();
		}
		@java.lang.Override
		public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.setField(field, value);
		}
		@java.lang.Override
		public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
			return super.clearField(field);
		}
		@java.lang.Override
		public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
			return super.clearOneof(oneof);
		}
		@java.lang.Override
		public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
				java.lang.Object value) {
			return super.setRepeatedField(field, index, value);
		}
		@java.lang.Override
		public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
			return super.addRepeatedField(field, value);
		}
		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.Message other) {
			if (other instanceof net.averak.gsync.schema.protobuf.player_api.error.ErrorCode) {
				return mergeFrom((net.averak.gsync.schema.protobuf.player_api.error.ErrorCode) other);
			} else {
				super.mergeFrom(other);
				return this;
			}
		}

		public Builder mergeFrom(net.averak.gsync.schema.protobuf.player_api.error.ErrorCode other) {
			if (other == net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.getDefaultInstance())
				return this;
			this.mergeUnknownFields(other.getUnknownFields());
			onChanged();
			return this;
		}

		@java.lang.Override
		public final boolean isInitialized() {
			return true;
		}

		@java.lang.Override
		public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0 :
							done = true;
							break;
						default : {
							if (!super.parseUnknownField(input, extensionRegistry, tag)) {
								done = true; // was an endgroup tag
							}
							break;
						} // default:
					} // switch (tag)
				} // while (!done)
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.unwrapIOException();
			} finally {
				onChanged();
			} // finally
			return this;
		}
		@java.lang.Override
		public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.setUnknownFields(unknownFields);
		}

		@java.lang.Override
		public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
			return super.mergeUnknownFields(unknownFields);
		}

		// @@protoc_insertion_point(builder_scope:gsync.player_api.error.ErrorCode)
	}

	// @@protoc_insertion_point(class_scope:gsync.player_api.error.ErrorCode)
	private static final net.averak.gsync.schema.protobuf.player_api.error.ErrorCode DEFAULT_INSTANCE;
	static {
		DEFAULT_INSTANCE = new net.averak.gsync.schema.protobuf.player_api.error.ErrorCode();
	}

	public static net.averak.gsync.schema.protobuf.player_api.error.ErrorCode getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	private static final com.google.protobuf.Parser<ErrorCode> PARSER = new com.google.protobuf.AbstractParser<ErrorCode>() {
		@java.lang.Override
		public ErrorCode parsePartialFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			Builder builder = newBuilder();
			try {
				builder.mergeFrom(input, extensionRegistry);
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(builder.buildPartial());
			} catch (com.google.protobuf.UninitializedMessageException e) {
				throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
						.setUnfinishedMessage(builder.buildPartial());
			}
			return builder.buildPartial();
		}
	};

	public static com.google.protobuf.Parser<ErrorCode> parser() {
		return PARSER;
	}

	@java.lang.Override
	public com.google.protobuf.Parser<ErrorCode> getParserForType() {
		return PARSER;
	}

	@java.lang.Override
	public net.averak.gsync.schema.protobuf.player_api.error.ErrorCode getDefaultInstanceForType() {
		return DEFAULT_INSTANCE;
	}

	public static final int HANDLING_TYPE_FIELD_NUMBER = 20000;
	/**
	 * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
	 */
	public static final com.google.protobuf.GeneratedMessage.GeneratedExtension<com.google.protobuf.DescriptorProtos.EnumValueOptions, net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.HandlingType> handlingType = com.google.protobuf.GeneratedMessage
			.newMessageScopedGeneratedExtension(
					net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.getDefaultInstance(), 0,
					net.averak.gsync.schema.protobuf.player_api.error.ErrorCode.HandlingType.class, null);
}
