package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.GameDto;
import net.averak.gsync.adapter.dao.dto.base.GameExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"all"})
public interface GameBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	long countByExample(GameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	int deleteByExample(GameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String gameId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	int insert(GameDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	int insertSelective(GameDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	List<GameDto> selectByExampleWithRowbounds(GameExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	List<GameDto> selectByExample(GameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	GameDto selectByPrimaryKey(String gameId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") GameDto row, @Param("example") GameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") GameDto row, @Param("example") GameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(GameDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_game
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(GameDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<GameDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(GameDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getGameId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<GameDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new GameExample();
		example.createCriteria().andGameIdIn(dtos.stream().map(GameDto::getGameId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(GameDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<GameDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}