package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.MasterVersionDto;
import net.averak.gsync.adapter.dao.dto.base.MasterVersionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"JavadocDeclaration", "DuplicatedCode"})
public interface MasterVersionBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	long countByExample(MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int deleteByExample(MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String version);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int insert(MasterVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int insertSelective(MasterVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	List<MasterVersionDto> selectByExampleWithRowbounds(MasterVersionExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	List<MasterVersionDto> selectByExample(MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	MasterVersionDto selectByPrimaryKey(String version);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") MasterVersionDto row, @Param("example") MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") MasterVersionDto row, @Param("example") MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MasterVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MasterVersionDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<MasterVersionDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(MasterVersionDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getVersion()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<MasterVersionDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new MasterVersionExample();
		example.createCriteria().andVersionIn(dtos.stream().map(MasterVersionDto::getVersion).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(MasterVersionDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<MasterVersionDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}