package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.MasterVersionDto;
import net.averak.gsync.adapter.dao.dto.base.MasterVersionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface MasterVersionBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	long countByExample(MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int deleteByExample(MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String version);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int insert(MasterVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int insertSelective(MasterVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	List<MasterVersionDto> selectByExampleWithRowbounds(MasterVersionExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	List<MasterVersionDto> selectByExample(MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	MasterVersionDto selectByPrimaryKey(String version);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") MasterVersionDto row, @Param("example") MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") MasterVersionDto row, @Param("example") MasterVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(MasterVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_master_version
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(MasterVersionDto row);
}