package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.OperatorDto;
import net.averak.gsync.adapter.dao.dto.base.OperatorExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface OperatorBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	long countByExample(OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int deleteByExample(OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String operatorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int insert(OperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int insertSelective(OperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	List<OperatorDto> selectByExampleWithRowbounds(OperatorExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	List<OperatorDto> selectByExample(OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	OperatorDto selectByPrimaryKey(String operatorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") OperatorDto row, @Param("example") OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") OperatorDto row, @Param("example") OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(OperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(OperatorDto row);
}