package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.OperatorDto;
import net.averak.gsync.adapter.dao.dto.base.OperatorExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"all"})
public interface OperatorBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	long countByExample(OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int deleteByExample(OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String operatorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int insert(OperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int insertSelective(OperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	List<OperatorDto> selectByExampleWithRowbounds(OperatorExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	List<OperatorDto> selectByExample(OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	OperatorDto selectByPrimaryKey(String operatorId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") OperatorDto row, @Param("example") OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") OperatorDto row, @Param("example") OperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(OperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(OperatorDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<OperatorDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(OperatorDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getOperatorId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<OperatorDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new OperatorExample();
		example.createCriteria().andOperatorIdIn(dtos.stream().map(OperatorDto::getOperatorId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(OperatorDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<OperatorDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}