package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PlayerBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	int insert(PlayerDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	List<PlayerDto> selectByExampleWithRowbounds(PlayerExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	List<PlayerDto> selectByExample(PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	PlayerDto selectByPrimaryKey(String playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerDto row, @Param("example") PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerDto row, @Param("example") PlayerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerDto row);
}