package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerLoginDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerLoginExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"all"})
public interface PlayerLoginBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int insert(PlayerLoginDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerLoginDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	List<PlayerLoginDto> selectByExampleWithRowbounds(PlayerLoginExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	List<PlayerLoginDto> selectByExample(PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	PlayerLoginDto selectByPrimaryKey(String playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerLoginDto row, @Param("example") PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerLoginDto row, @Param("example") PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerLoginDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerLoginDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<PlayerLoginDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(PlayerLoginDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getPlayerId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<PlayerLoginDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new PlayerLoginExample();
		example.createCriteria().andPlayerIdIn(dtos.stream().map(PlayerLoginDto::getPlayerId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(PlayerLoginDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<PlayerLoginDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}