package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerLoginDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerLoginExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PlayerLoginBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int insert(PlayerLoginDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerLoginDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	List<PlayerLoginDto> selectByExampleWithRowbounds(PlayerLoginExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	List<PlayerLoginDto> selectByExample(PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	PlayerLoginDto selectByPrimaryKey(String playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerLoginDto row, @Param("example") PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerLoginDto row, @Param("example") PlayerLoginExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerLoginDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_login
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerLoginDto row);
}