package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerProfileDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerProfileExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PlayerProfileBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	int insert(PlayerProfileDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerProfileDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	List<PlayerProfileDto> selectByExampleWithRowbounds(PlayerProfileExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	List<PlayerProfileDto> selectByExample(PlayerProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	PlayerProfileDto selectByPrimaryKey(String playerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerProfileDto row, @Param("example") PlayerProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerProfileDto row, @Param("example") PlayerProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerProfileDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_profile
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerProfileDto row);
}