package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerStorageRevisionDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerStorageRevisionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"JavadocDeclaration", "DuplicatedCode"})
public interface PlayerStorageRevisionBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerStorageRevisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerStorageRevisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("playerId") String playerId, @Param("tenantId") String tenantId,
			@Param("playerStorageRevisionId") String playerStorageRevisionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	int insert(PlayerStorageRevisionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerStorageRevisionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageRevisionDto> selectByExampleWithRowbounds(PlayerStorageRevisionExample example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageRevisionDto> selectByExample(PlayerStorageRevisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	PlayerStorageRevisionDto selectByPrimaryKey(@Param("playerId") String playerId, @Param("tenantId") String tenantId,
			@Param("playerStorageRevisionId") String playerStorageRevisionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerStorageRevisionDto row,
			@Param("example") PlayerStorageRevisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerStorageRevisionDto row,
			@Param("example") PlayerStorageRevisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerStorageRevisionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_revision
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerStorageRevisionDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<PlayerStorageRevisionDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(PlayerStorageRevisionDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getPlayerId(), dto.getTenantId(), dto.getPlayerStorageRevisionId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<PlayerStorageRevisionDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new PlayerStorageRevisionExample();
		example.createCriteria().andPlayerIdIn(dtos.stream().map(PlayerStorageRevisionDto::getPlayerId).toList());
		example.createCriteria().andTenantIdIn(dtos.stream().map(PlayerStorageRevisionDto::getTenantId).toList());
		example.createCriteria().andPlayerStorageRevisionIdIn(
				dtos.stream().map(PlayerStorageRevisionDto::getPlayerStorageRevisionId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(PlayerStorageRevisionDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<PlayerStorageRevisionDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}