package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerFriendRequestDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerFriendRequestExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"JavadocDeclaration", "DuplicatedCode"})
public interface PlayerFriendRequestBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerFriendRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerFriendRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("playerId") String playerId, @Param("receiverPlayerId") String receiverPlayerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	int insert(PlayerFriendRequestDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerFriendRequestDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	List<PlayerFriendRequestDto> selectByExampleWithRowbounds(PlayerFriendRequestExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	List<PlayerFriendRequestDto> selectByExample(PlayerFriendRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	PlayerFriendRequestDto selectByPrimaryKey(@Param("playerId") String playerId,
			@Param("receiverPlayerId") String receiverPlayerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerFriendRequestDto row,
			@Param("example") PlayerFriendRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerFriendRequestDto row, @Param("example") PlayerFriendRequestExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerFriendRequestDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend_request
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerFriendRequestDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<PlayerFriendRequestDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(PlayerFriendRequestDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getPlayerId(), dto.getReceiverPlayerId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<PlayerFriendRequestDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new PlayerFriendRequestExample();
		example.createCriteria().andPlayerIdIn(dtos.stream().map(PlayerFriendRequestDto::getPlayerId).toList());
		example.createCriteria()
				.andReceiverPlayerIdIn(dtos.stream().map(PlayerFriendRequestDto::getReceiverPlayerId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(PlayerFriendRequestDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<PlayerFriendRequestDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}