package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerStorageEntryDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerStorageEntryExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"JavadocDeclaration", "DuplicatedCode"})
public interface PlayerStorageEntryBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("playerId") String playerId, @Param("tenantId") String tenantId,
			@Param("key") String key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int insert(PlayerStorageEntryDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerStorageEntryDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageEntryDto> selectByExampleWithBLOBsWithRowbounds(PlayerStorageEntryExample example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageEntryDto> selectByExampleWithBLOBs(PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageEntryDto> selectByExampleWithRowbounds(PlayerStorageEntryExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageEntryDto> selectByExample(PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	PlayerStorageEntryDto selectByPrimaryKey(@Param("playerId") String playerId, @Param("tenantId") String tenantId,
			@Param("key") String key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerStorageEntryDto row,
			@Param("example") PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByExampleWithBLOBs(@Param("row") PlayerStorageEntryDto row,
			@Param("example") PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerStorageEntryDto row, @Param("example") PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerStorageEntryDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(PlayerStorageEntryDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerStorageEntryDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<PlayerStorageEntryDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(PlayerStorageEntryDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getPlayerId(), dto.getTenantId(), dto.getKey()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<PlayerStorageEntryDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new PlayerStorageEntryExample();
		example.createCriteria().andPlayerIdIn(dtos.stream().map(PlayerStorageEntryDto::getPlayerId).toList());
		example.createCriteria().andTenantIdIn(dtos.stream().map(PlayerStorageEntryDto::getTenantId).toList());
		example.createCriteria().andKeyIn(dtos.stream().map(PlayerStorageEntryDto::getKey).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(PlayerStorageEntryDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKeyWithBLOBs(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<PlayerStorageEntryDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKeyWithBLOBs(dto);
		});
	}
}