package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerStorageEntryDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerStorageEntryExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PlayerStorageEntryBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("playerId") String playerId, @Param("tenantId") String tenantId,
			@Param("key") String key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int insert(PlayerStorageEntryDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerStorageEntryDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageEntryDto> selectByExampleWithBLOBsWithRowbounds(PlayerStorageEntryExample example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageEntryDto> selectByExampleWithBLOBs(PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageEntryDto> selectByExampleWithRowbounds(PlayerStorageEntryExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	List<PlayerStorageEntryDto> selectByExample(PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	PlayerStorageEntryDto selectByPrimaryKey(@Param("playerId") String playerId, @Param("tenantId") String tenantId,
			@Param("key") String key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerStorageEntryDto row,
			@Param("example") PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByExampleWithBLOBs(@Param("row") PlayerStorageEntryDto row,
			@Param("example") PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerStorageEntryDto row, @Param("example") PlayerStorageEntryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerStorageEntryDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeyWithBLOBs(PlayerStorageEntryDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_storage_entry
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerStorageEntryDto row);
}