package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.PlayerFriendDto;
import net.averak.gsync.adapter.dao.dto.base.PlayerFriendExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"JavadocDeclaration", "DuplicatedCode"})
public interface PlayerFriendBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	long countByExample(PlayerFriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	int deleteByExample(PlayerFriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("playerId") String playerId, @Param("friendPlayerId") String friendPlayerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	int insert(PlayerFriendDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	int insertSelective(PlayerFriendDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	List<PlayerFriendDto> selectByExampleWithRowbounds(PlayerFriendExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	List<PlayerFriendDto> selectByExample(PlayerFriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	PlayerFriendDto selectByPrimaryKey(@Param("playerId") String playerId,
			@Param("friendPlayerId") String friendPlayerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") PlayerFriendDto row, @Param("example") PlayerFriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") PlayerFriendDto row, @Param("example") PlayerFriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(PlayerFriendDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_player_friend
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(PlayerFriendDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<PlayerFriendDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(PlayerFriendDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getPlayerId(), dto.getFriendPlayerId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<PlayerFriendDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new PlayerFriendExample();
		example.createCriteria().andPlayerIdIn(dtos.stream().map(PlayerFriendDto::getPlayerId).toList());
		example.createCriteria().andFriendPlayerIdIn(dtos.stream().map(PlayerFriendDto::getFriendPlayerId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(PlayerFriendDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<PlayerFriendDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}