package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.RequiredClientVersionDto;
import net.averak.gsync.adapter.dao.dto.base.RequiredClientVersionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface RequiredClientVersionBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	long countByExample(RequiredClientVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	int deleteByExample(RequiredClientVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("masterVersion") String masterVersion, @Param("clientVersion") String clientVersion,
			@Param("platform") Long platform);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	int insert(RequiredClientVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	int insertSelective(RequiredClientVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	List<RequiredClientVersionDto> selectByExampleWithRowbounds(RequiredClientVersionExample example,
			RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	List<RequiredClientVersionDto> selectByExample(RequiredClientVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	RequiredClientVersionDto selectByPrimaryKey(@Param("masterVersion") String masterVersion,
			@Param("clientVersion") String clientVersion, @Param("platform") Long platform);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") RequiredClientVersionDto row,
			@Param("example") RequiredClientVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") RequiredClientVersionDto row,
			@Param("example") RequiredClientVersionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RequiredClientVersionDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_required_client_version
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RequiredClientVersionDto row);
}