package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.RGameOperatorDto;
import net.averak.gsync.adapter.dao.dto.base.RGameOperatorExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"all"})
public interface RGameOperatorBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	long countByExample(RGameOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	int deleteByExample(RGameOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("operatorId") String operatorId, @Param("gameId") String gameId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	int insert(RGameOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	int insertSelective(RGameOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	List<RGameOperatorDto> selectByExampleWithRowbounds(RGameOperatorExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	List<RGameOperatorDto> selectByExample(RGameOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	RGameOperatorDto selectByPrimaryKey(@Param("operatorId") String operatorId, @Param("gameId") String gameId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") RGameOperatorDto row, @Param("example") RGameOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") RGameOperatorDto row, @Param("example") RGameOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RGameOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_game_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RGameOperatorDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<RGameOperatorDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(RGameOperatorDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getOperatorId(), dto.getGameId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<RGameOperatorDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new RGameOperatorExample();
		example.createCriteria().andOperatorIdIn(dtos.stream().map(RGameOperatorDto::getOperatorId).toList());
		example.createCriteria().andGameIdIn(dtos.stream().map(RGameOperatorDto::getGameId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(RGameOperatorDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<RGameOperatorDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}