package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.RTenantOperatorDto;
import net.averak.gsync.adapter.dao.dto.base.RTenantOperatorExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface RTenantOperatorBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	long countByExample(RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int deleteByExample(RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("operatorId") String operatorId, @Param("tenantId") String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int insert(RTenantOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int insertSelective(RTenantOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	List<RTenantOperatorDto> selectByExampleWithRowbounds(RTenantOperatorExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	List<RTenantOperatorDto> selectByExample(RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	RTenantOperatorDto selectByPrimaryKey(@Param("operatorId") String operatorId, @Param("tenantId") String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") RTenantOperatorDto row,
			@Param("example") RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") RTenantOperatorDto row, @Param("example") RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RTenantOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RTenantOperatorDto row);
}