package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.RTenantOperatorDto;
import net.averak.gsync.adapter.dao.dto.base.RTenantOperatorExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"JavadocDeclaration", "DuplicatedCode"})
public interface RTenantOperatorBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	long countByExample(RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int deleteByExample(RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(@Param("operatorId") String operatorId, @Param("tenantId") String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int insert(RTenantOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int insertSelective(RTenantOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	List<RTenantOperatorDto> selectByExampleWithRowbounds(RTenantOperatorExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	List<RTenantOperatorDto> selectByExample(RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	RTenantOperatorDto selectByPrimaryKey(@Param("operatorId") String operatorId, @Param("tenantId") String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") RTenantOperatorDto row,
			@Param("example") RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") RTenantOperatorDto row, @Param("example") RTenantOperatorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(RTenantOperatorDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_r_tenant_operator
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(RTenantOperatorDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<RTenantOperatorDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(RTenantOperatorDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getOperatorId(), dto.getTenantId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<RTenantOperatorDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new RTenantOperatorExample();
		example.createCriteria().andOperatorIdIn(dtos.stream().map(RTenantOperatorDto::getOperatorId).toList());
		example.createCriteria().andTenantIdIn(dtos.stream().map(RTenantOperatorDto::getTenantId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(RTenantOperatorDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<RTenantOperatorDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}