package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.TenantDto;
import net.averak.gsync.adapter.dao.dto.base.TenantExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
@SuppressWarnings({"JavadocDeclaration", "DuplicatedCode"})
public interface TenantBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	long countByExample(TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int deleteByExample(TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int insert(TenantDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int insertSelective(TenantDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	List<TenantDto> selectByExampleWithRowbounds(TenantExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	List<TenantDto> selectByExample(TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	TenantDto selectByPrimaryKey(String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") TenantDto row, @Param("example") TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") TenantDto row, @Param("example") TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TenantDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TenantDto row);

	/**
	 * 複数レコードを一括で INSERT する
	 *
	 * @mbg.generated
	 */
	void bulkInsert(@Param("dtos") List<TenantDto> dtos);

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(TenantDto dto) {
		dto.setOriginal(selectByPrimaryKey(dto.getTenantId()));
	}

	/**
	 * PK でレコード検索し、存在する場合は original にセットする
	 *
	 * @mbg.generated
	 */
	default void syncOriginal(List<TenantDto> dtos) {
		if (dtos.isEmpty()) {
			return;
		}

		final var example = new TenantExample();
		example.createCriteria().andTenantIdIn(dtos.stream().map(TenantDto::getTenantId).toList());
		final var originals = selectByExample(example);
		originals.forEach(original -> dtos.forEach(dto -> {
			if (dto.isPrimaryKeyEquals(original)) {
				dto.setOriginal(original);
			}
		}));
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(TenantDto dto) {
		if (dto.getOriginal() == null) {
			insert(dto);
		} else {
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		}
	}

	/**
	 * original が null の場合は INSERT、そうでない場合は UPDATE を実行する
	 *
	 * @mbg.generated
	 */
	default void insertOrUpdate(List<TenantDto> dtos) {
		final var inserts = dtos.stream().filter(dto -> dto.getOriginal() == null).toList();
		if (!inserts.isEmpty()) {
			bulkInsert(inserts);
		}

		final var updates = dtos.stream().filter(dto -> dto.getOriginal() != null).toList();
		updates.parallelStream().forEach(dto -> {
			if (dto.getOriginal() == null) {
				return;
			}
			dto.setCreatedAt(dto.getOriginal().getCreatedAt());
			updateByPrimaryKey(dto);
		});
	}
}