package net.averak.gsync.adapter.dao.mapper.base;

import java.util.List;
import net.averak.gsync.adapter.dao.dto.base.TenantDto;
import net.averak.gsync.adapter.dao.dto.base.TenantExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TenantBaseMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	long countByExample(TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int deleteByExample(TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int insert(TenantDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int insertSelective(TenantDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	List<TenantDto> selectByExampleWithRowbounds(TenantExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	List<TenantDto> selectByExample(TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	TenantDto selectByPrimaryKey(String tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") TenantDto row, @Param("example") TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") TenantDto row, @Param("example") TenantExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TenantDto row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table gsync_tenant
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TenantDto row);
}