// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource/player.proto

// Protobuf Java Version: 3.25.2
package net.averak.gsync.schema.protobuf.resource.player;

public interface PlayerProfileOrBuilder
		extends
			// @@protoc_insertion_point(interface_extends:gsync.resource.player.PlayerProfile)
			com.google.protobuf.MessageOrBuilder {

	/**
	 * <code>string nickname = 1;</code>
	 * 
	 * @return The nickname.
	 */
	java.lang.String getNickname();
	/**
	 * <code>string nickname = 1;</code>
	 * 
	 * @return The bytes for nickname.
	 */
	com.google.protobuf.ByteString getNicknameBytes();

	/**
	 * <code>string icon_id = 2;</code>
	 * 
	 * @return The iconId.
	 */
	java.lang.String getIconId();
	/**
	 * <code>string icon_id = 2;</code>
	 * 
	 * @return The bytes for iconId.
	 */
	com.google.protobuf.ByteString getIconIdBytes();
}
